overc: enable peer containers
The OverC system architecture has a container command and control
structure that is consolidated in dom0. The control domain has the
ability to launch VMs and containers.

Containers can be of two flavours: nested or peer.

While launched from dom0, peer containers have their namespaces
directly inherited from the essential layer of the system. This
allows them to operate independently from other containers (and
dom0 itself) from the point of view of resources and constraints.

The initial launch and implementation of container launch only
created peer network namespaces. This is was not the intended design
and was only a stepping stone.

Since the kernel currently does not allow a child namespace to
enter the parent namespaces of proc & user, we must proxy peer
container commands through an agent running within the base/essential
namespace.

The cube-cmd-server provides this agent/proxy, and it is modified
appropriately to execute container management tasks on behalf of
authorized containers (currently only dom0) as specified in the
configuration file.

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>

diff --git a/meta-cube/recipes-support/cube-cmd-server/files/cube-cmd-server b/meta-cube/recipes-support/cube-cmd-server/files/cube-cmd-server
--- a/meta-cube/recipes-support/cube-cmd-server/files/cube-cmd-server
+++ b/meta-cube/recipes-support/cube-cmd-server/files/cube-cmd-server
@@ -57,9 +57,11 @@ function parse_yaml_conf_file() {
     }' | sed 's/_=/+=/g'
 }
 
-function create_console_listner() {
-    local listnername=$1
+function create_console_listener() {
+    local listenername=$1
     local connectorname=$2
+    local type=$3 # console or namespace
+    local target=$4
     local matches=""
 
     # only lxc is currently supported
@@ -78,11 +80,39 @@ function create_console_listner() {
 	    if [ -n "${verbose}" ]; then
 		debug="-d -d"
 	    fi
-	    socat $debug pty,raw,echo=0,mode=666,link=/opt/container/${cname}/console-${listnername} "exec:/sbin/agetty -J - linux,pty,setsid,stderr,ctty" &
+
+	    if [ -z "$type" ]; then
+		type=console
+	    fi
+
+	    if [ "${type}" = "console" ]; then
+		socat $debug pty,raw,echo=0,mode=666,link=/opt/container/${cname}/console-${listenername} "exec:/sbin/agetty -J - linux,pty,setsid,stderr,ctty" &
+	    fi
+	    if [ "${type}" = "namespace" ]; then
+		# namespace enter!
+		if [ -n "$target" ]; then
+		    socat $debug pty,raw,echo=0,mode=666,link=/opt/container/${cname}/namespace-${target} "exec:lxc-attach -n ${target} /bin/bash,pty,setsid,stderr,ctty"
+		else
+		    echo "[ERROR]: namespace consoles require a target container"
+		fi
+	    fi
 	done
     else
 	echo "[ERROR]: no requestor matching ${connectorname} found, no console created"
     fi
+}
+
+function do_lxc_command()
+{
+    local cname=$1
+    shift
+    local command=$@
+
+    # We run this within socat to allow for ptys, pipes, etc, to be used
+    # in the future. For now, we just dump the output to the waiting pipe.
+    # if no one is there, the output is lost.
+    # TODO: see if a timeout is required
+    socat -u EXEC:"${command}" PIPE:/opt/container/${cname}/cmd-output
 }
 
 ##############  Mainline begins here ################################
@@ -204,6 +234,32 @@ while (true) do
 		    echo "[INFO]: switching requestor to ${requestor}"
 		fi
 		;;
+	    lxc*)
+		echo ${commands_lxc_acl[@]} | grep -q ${requestor}
+		if [ $? -eq 0 ]; then
+		    if [ -n "${verbose}" ]; then
+			echo "[INFO]: lxc command: $line"
+		    fi
+		    do_lxc_command ${requestor} $line
+		else
+		    echo "[INFO]: requestor ($requestor) is not allowed to issue lxc commands"
+		fi
+		;;
+	    nsenter*)
+		# only available to dom0
+		echo ${commands_nsenter_acl[@]} | grep -q ${requestor}
+		if [ $? -eq 0 ]; then
+		    echo "[INFO]: entering namespace: $line"
+		    target=`echo $line | cut -d' ' -f2`
+		    if [ -n "${target}" ]; then
+			create_console_listener ${whoami} ${requestor} namespace ${target}
+		    else
+			cho "[INFO]: a valid target container is required"
+		    fi
+		else
+		    echo "[INFO]: requestor ($requestor) is not allowed to issue nsenter"
+		fi
+		;;
 	    console*)
 		if [ -n "${verbose}" ]; then
 		    echo "[INFO]: console creation request: $line"
@@ -211,7 +267,7 @@ while (true) do
 		if [ -z "${requestor}" ]; then
 		    echo "[ERROR]: console command requires a requestor hostname"
 		fi
-		create_console_listner ${whoami} ${requestor}
+		create_console_listener ${whoami} ${requestor}
 		;;
 	    poweroff)
 		if [ -z "${requestor}" ]; then
diff --git a/meta-cube/recipes-support/dom0-contctl/files/dom0_contctl b/meta-cube/recipes-support/dom0-contctl/files/dom0_contctl
--- a/meta-cube/recipes-support/dom0-contctl/files/dom0_contctl
+++ b/meta-cube/recipes-support/dom0-contctl/files/dom0_contctl
@@ -105,6 +105,21 @@ ${0##*/} remote-net [option]...
 EOF
 }
 
+# XXX: TODO: this really should be wrapped as a standalone command!
+function do_essential_cmd()
+{
+    local cmd=$@
+
+    if [ -e "/opt/container/local/cmd-pipe" ]; then
+	# the command
+	echo "${cmd}" > /opt/container/local/cmd-pipe
+	# the output
+	socat -u PIPE:/opt/container/local/cmd-output -
+    else
+	echo "ERROR: command channel is not available at /opt/container/local/cmd-pipe"
+	exit 1
+    fi
+}
 
 # Global variables
 # What container type we support
diff --git a/meta-cube/recipes-support/overc-utils/source/cube-console b/meta-cube/recipes-support/overc-utils/source/cube-console
--- a/meta-cube/recipes-support/overc-utils/source/cube-console
+++ b/meta-cube/recipes-support/overc-utils/source/cube-console
@@ -132,6 +132,67 @@ function do_dom0_console()
     socat -,raw,echo=0 /opt/container/local/console-dom0
 }
 
+function do_dom0_console()
+{
+    if [ ! -e "/opt/container/local/cmd-pipe" ]; then
+	echo "[ERROR]: /opt/container/local/cmd-pipe not found, cannot create console to dom0"
+	exit 1
+    fi
+
+    # In the future, we can create more .. but for now, let's just allow one
+    if [ -e "/opt/container/local/console-dom0" ]; then
+	echo "[INFO]: the dom0 console is already active, only one connection is allowed"
+	exit 1
+    fi
+
+    echo "console" > /opt/container/local/cmd-pipe
+
+    for i in `seq 0 9`; do
+	if [ ! -e "/opt/container/local/console-dom0" ]; then
+	    sleep 1
+	fi
+    done
+
+    if [ ! -e "/opt/container/local/console-dom0" ]; then
+	echo "[ERROR]: /opt/container/local/console-dom0 was not created, cannot connect to dom0"
+	exit 1
+    fi
+
+    socat -,raw,echo=0 /opt/container/local/console-dom0
+}
+
+# Note: this can be unified with the dom0 console.
+function do_namespace_console()
+{
+    local target=$1
+
+    if [ ! -e "/opt/container/local/cmd-pipe" ]; then
+	echo "[ERROR]: /opt/container/local/cmd-pipe not found, cannot create console"
+	exit 1
+    fi
+
+    # In the future, we can create more .. but for now, let's just allow one
+    if [ -e "/opt/container/local/namespace-${target}" ]; then
+	echo "[INFO]: the namespace is already active, only one connection is allowed"
+	exit 1
+    fi
+
+    echo "nsenter ${target}" > /opt/container/local/cmd-pipe
+
+    for i in `seq 0 9`; do
+	if [ ! -e "/opt/container/local/namespace-${target}" ]; then
+	    sleep 1
+	fi
+    done
+
+    if [ ! -e "/opt/container/local/namespace-${target}" ]; then
+	echo "[ERROR]: /opt/container/local/namespace-${target} was not created, cannot connect to namespace"
+	exit 1
+    fi
+
+    socat -,raw,echo=0 /opt/container/local/namespace-${target}
+}
+
 # Parms: $1 = filename
 function enter_console
 {
@@ -149,7 +210,9 @@ function enter_console
 	    do_dom0_console
 	    ;;
 	*)
-	    echo "ERROR: Unknown cube, cannot enter console"
+	    # only works if you are on dom0, since these are unauthenticated
+	    # consoles
+	    do_namespace_console ${consolename}
 	    ;;
     esac
 }
