meta-overc: snapshot containers conditionally
If available diskspace is smaller than the upgrading container's
image size, abandon snapshot it and upgrading directly, otherwise
snapshot it before do upgrading.

Signed-off-by: fli <fupan.li@windriver.com>

diff --git a/meta-cube/recipes-support/overc-system-agent/files/overc-system-agent-1.2/container-scripts/dom0 b/meta-cube/recipes-support/overc-system-agent/files/overc-system-agent-1.2/container-scripts/dom0
--- a/meta-cube/recipes-support/overc-system-agent/files/overc-system-agent-1.2/container-scripts/dom0
+++ b/meta-cube/recipes-support/overc-system-agent/files/overc-system-agent-1.2/container-scripts/dom0
@@ -305,6 +305,31 @@ runcmd_in_container() {
 	$DOM0_CTL exec-cmd -n $1 $2
 }
 
+format_size() {
+	local size=$1
+	size_unit=${size: -1}
+	size_num=`echo $size | sed "s/${size_unit}//"`
+
+        case $size_unit in
+		"K")
+			num=`echo "$size_num*1000"|bc`
+			echo $((${num//.*/+1}))
+			;;
+		"M")
+			num=`echo "$size_num*1000*1000"|bc`
+			echo $((${num//.*/+1}))
+			;;
+		"G")
+			num=`echo "$size_num*1000*1000*1000"|bc`
+			echo $((${num//.*/+1}))
+			;;
+		"*")
+			echo "Error! cannot recognize size"
+			exit 1
+			;;
+	esac
+}
+
 rpm_upgrade() {
 	local container=$1
 
@@ -318,8 +343,19 @@ rpm_upgrade() {
 		return 0
 	fi
 
-	echo "snapshots on container: $container"
-	snapshot $container
+	c_raw_size=`du -hs /var/lib/lxc/${container}/rootfs | awk '{print $1}'`
+	c_size=`format_size $c_raw_size`
+	a_raw_size=`df -ha /var/lib/lxc/overc-containers | sed -n '2p' | awk '{print $4}'`
+	a_size=`format_size $a_raw_size`
+
+	if [ $a_size -ge $c_size ]; then
+		echo "snapshots on container: $container"
+		snapshot $container
+	else
+		echo "*******************************************************************"
+		echo "  Warning: There isn't enough space left to snapshot conainer"
+		echo "*******************************************************************"
+	fi
 
 	tempdir="/tmp/tmpd.$RANDOM"
 	runcmd_in_container $container "mkdir -p $tempdir"
