c3-construct: allow both #defined and aliased commands
If a command was both #define'd (for a symlink) and had an
override, then the command wouldn't work since the "real command"
wasn't know and the wrapper not called properly.

We fixup our processing to allow both to be valid in the same
construct run.

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>

diff --git a/meta-cube/recipes-support/overc-utils/source/c3-construct b/meta-cube/recipes-support/overc-utils/source/c3-construct
--- a/meta-cube/recipes-support/overc-utils/source/c3-construct
+++ b/meta-cube/recipes-support/overc-utils/source/c3-construct
@@ -607,7 +607,9 @@ do_construct()
 	#       now, that is fine. This shouldn't be written in bash if we want that
 	#       sort of scalability
 	#
-	for f in ${fns} ${fns_to_alias}; do
+
+	i_list=$(echo "${fns} ${fns_to_alias}" | tr ' ' '\n' | sort | uniq | xargs)
+	for f in ${i_list}; do
 	    program_to_find="${f}"
 	    var_for_use_in_env="${f}"
 
@@ -624,13 +626,17 @@ do_construct()
 	    if [ ${DEFINE_MAP[$f]+isset} ]; then
 		if [ -z "${DEFINE_MAP[$f]}" ]; then
 		    alias=t
+		    echo "${fns}" | grep -q -w "${f}"
+		    if [ $? -eq 0 ]; then
+			mapping=t
+		    fi
 		else
 		    mapping=t
 		fi
 	    else
 		mapping=t
 	    fi
-	    
+
 	    # Get all the keys, see what they are mapped to, the mapped value may
 	    # match a function provided in the routine. This allows us to determine
 	    # that a symbol was translated in the input file, and we should look for
@@ -647,58 +653,61 @@ do_construct()
 	    if [ -n "${mapping}" ]; then
 		#echo "making a variable ${var_for_use_in_env}=${real_program}"
 		declare -g "${var_for_use_in_env}=${real_program}"
-	    else
-		if [ -n "${verbose}" ]; then
-		    echo "[INFO]: making an alias $f to ${real_program}"
+	    fi
+	    if [ -n "${alias}" ]; then
+		if [ -z "${real_program}" ]; then
+		    real_program=$(which false)
 		fi
-		eval alias $f="${real_program}"
+		if [ -n "${verbose}" ]; then
+		    echo "[INFO]: linking $f to ${real_program}"
+		fi
 		ln -sf ${real_program} ${c3_tmpdir}/bin/${program_to_find}
 	    fi
 	done
 
-        for z in ${cmds_to_override}; do
-            if [ -n "${verbose}" ]; then
-                echo "[INFO]: disabling command: $z"
-            fi
+	for z in ${cmds_to_override}; do
+	    if [ -n "${verbose}" ]; then
+		echo "[INFO]: disabling command: $z"
+	    fi
 	    # Note: this only works for .cmds that have a single function
 	    #       which matches the name of the command
-            override_function $(basename "$z" .cmd)
-        done
+	    override_function $(basename "$z" .cmd)
+	done
 
-        unset PATH
-        (
-            set -e
+	unset PATH
+	(
+	    set -e
 	    export PATH="${c3_tmpdir}/bin"
 	    eval . $in 2> ${c3_output_file} 1> ${c3_good_output}
-        )
+	)
     )
 
     if [ $? -ne 0 ]; then
-        echo "[ERROR]: processing of file $in failed"
+	echo "[ERROR]: processing of file $in failed"
 
-        cat ${c3_output_file}
+	cat ${c3_output_file}
 
-        # look for common errors so we can point to the right input file
+	# look for common errors so we can point to the right input file
 
-        # 1) /tmp/tmp.gfN6WsbDHN: line 403: cat: No such file or directory
-        #     "grep -oh" will only output what matches, which gets us "line 404: .."
-        #     cut gets us the second field, which is the line number
-        line=$(cat ${c3_output_file} | grep -oh "line.*:" | cut -f2 -d' ' | sed 's/://g')
-        if [ -n "$line" ]; then
-            let start_line=$line-20
-            let end_line=$line+10
-            if [ $start_line -lt 0 ]; then
-                start_line=1
-            fi
-            echo ""
-            echo "Context around the error is:"
-            echo ""
-            sed -n -e "$start_line,$end_line p" -e "$end_line q" $in | sed 's/^/    /'
-            echo ""
-            echo "See pre-processed file $in for more details"
-        fi
+	# 1) /tmp/tmp.gfN6WsbDHN: line 403: cat: No such file or directory
+	#     "grep -oh" will only output what matches, which gets us "line 404: .."
+	#     cut gets us the second field, which is the line number
+	line=$(cat ${c3_output_file} | grep -oh "line.*:" | cut -f2 -d' ' | sed 's/://g')
+	if [ -n "$line" ]; then
+	    let start_line=$line-20
+	    let end_line=$line+10
+	    if [ $start_line -lt 0 ]; then
+		start_line=1
+	    fi
+	    echo ""
+	    echo "Context around the error is:"
+	    echo ""
+	    sed -n -e "$start_line,$end_line p" -e "$end_line q" $in | sed 's/^/    /'
+	    echo ""
+	    echo "See pre-processed file $in for more details"
+	fi
 	rm -f ${c3_output_file}
-        exit 1
+	exit 1
     elif [ -n "${verbose}" ]; then
         cat ${c3_output_file}
 	cat ${c3_good_output}
