consoles: allow multiple consoles
The first implementation of the command server only allowed one
connection between two cubes. While not a serious limitation, it
is uncessary.

With this change, a dynamically numbered console pipe is created
and returned to the calling console command. The console then
hooks up to that pipe versus a hard coded name.

We also fork the console in the background on the command server
side, leaving us available to handle more requests.

The combination of the two means that multiple console are now
possible.

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>

diff --git a/meta-cube/recipes-support/overc-utils/source/cube-console b/meta-cube/recipes-support/overc-utils/source/cube-console
--- a/meta-cube/recipes-support/overc-utils/source/cube-console
+++ b/meta-cube/recipes-support/overc-utils/source/cube-console
@@ -80,16 +80,9 @@ function do_essential_console()
 	exit 1
     fi
 
-    # In the future, we can create more .. but for now, let's just allow one
-    console_pipe=`ls /opt/container/local/console-essential 2> /dev/null`
-    if [ -n "${console_pipe}" ]; then
-    	echo "[INFO]: the essential console is already active, only one connection is allowed"
-    	exit 1
-    fi
-
     echo "console essential" > /opt/container/local/cmd-pipe
 
-    file=`wait_for_files 10 /opt/container/local/console-essential /opt/container/local/cmd-error`
+    file=`wait_for_files 10 /opt/container/local/cmd-output /opt/container/local/cmd-error`
     if [ -z "${file}" ]; then
 	echo "[ERROR]: No console is available, and no error reported"
 	exit 2
@@ -98,7 +91,15 @@ function do_essential_console()
 	socat -,raw,echo=0 ${file}
 	exit 1
     fi
+    if [ "${file}" = "/opt/container/local/cmd-output" ]; then
+	console_device=`cat ${file} | sed 's/\r//g'`
+    fi
 
+    file=`wait_for_files 10 /opt/container/local/${console_device}`
+    if [ -z "${file}" ]; then
+	echo "[ERROR]: No console is available, and no error reported"
+	exit 2
+    fi
     socat -,raw,echo=0 ${file}
 }
 
@@ -129,7 +130,7 @@ function do_console()
 	echo "console ${target}" > /opt/container/local/cmd-pipe
     fi
 
-    file=`wait_for_files 10 /opt/container/local/console-${target} /opt/container/local/cmd-error`
+    file=`wait_for_files 10 /opt/container/local/cmd-output /opt/container/local/cmd-error`
     if [ -z "${file}" ]; then
 	echo "[ERROR]: No console is available, and no error reported"
 	exit 2
@@ -138,8 +139,16 @@ function do_console()
 	socat -,raw,echo=0 ${file}
 	exit 1
     fi
+    if [ "${file}" = "/opt/container/local/cmd-output" ]; then
+	console_device=`cat ${file} | sed 's/\r//g'`
+    fi
 
-    socat -,raw,echo=0 /opt/container/local/console-${target}
+    file=`wait_for_files 10 /opt/container/local/${console_device}`
+    if [ -z "${file}" ]; then
+	echo "[ERROR]: No console is available, and no error reported"
+	exit 2
+    fi
+    socat -,raw,echo=0 ${file}
 }
 
 # Parms: $1: target container/console
