cube-cfg: Print error and exit if config.json fails to generate
If the oct-tools have changed an argument the generator fails for any
reason we should stop immediately.

Signed-off-by: Jason Wessel <jason.wessel@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>

diff --git a/meta-cube/recipes-support/overc-utils/source/cube-cfg b/meta-cube/recipes-support/overc-utils/source/cube-cfg
--- a/meta-cube/recipes-support/overc-utils/source/cube-cfg
+++ b/meta-cube/recipes-support/overc-utils/source/cube-cfg
@@ -564,6 +564,10 @@ IFS='
                      ${capabilities} \
                      ${mount_args} \
                      > config.json.tmp
+    if [ ! -s config.json.tmp ] ; then
+	echo "ERROR: config.jason generation failed"
+	exit 1
+    fi
 
     # fixup: disable seccomp completely by making it a section that is ignored
     sed -i 's/\"seccomp\"/\"seccomp-ignore\"/g' config.json.tmp
