cube-cfg: add 'attributes' configuration, and allow cube-cfg to display them
We add the ability to tag containers with attributes, netprime being the
first example of a use case.

We also modify cube-cfg to display the attributes when a detailed listing
is requested.

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>

diff --git a/meta-cube/recipes-support/overc-utils/source/cube-cfg b/meta-cube/recipes-support/overc-utils/source/cube-cfg
--- a/meta-cube/recipes-support/overc-utils/source/cube-cfg
+++ b/meta-cube/recipes-support/overc-utils/source/cube-cfg
@@ -71,6 +71,10 @@ cat << EOF
 
     get the unique machine / platform identifier
 
+ ${0##*/} [-n <container name>] attribute [+][-] <attribute>
+
+    associated an attribute with a container. + to add, - to remove.
+
  ${0##*/} get/set:
 
    NOTE: variables with embedded / are etcd set/get operations.
@@ -391,6 +395,14 @@ IFS='
 	    done
 	fi
 IFS=$OLDIFS
+    fi
+
+    if [ -e "${out_dir}/cube.attributes" ]; then
+	echo ""
+	echo "attributes:"
+	echo "-----------"
+	cat "${out_dir}/cube.attributes"
+	echo ""
     fi
 
     echo ""
@@ -784,6 +796,65 @@ case "${cmd}" in
 	else
 	    echo ""
 	fi
+	;;
+    attribute)
+	op=${cmd_options_non_dashed[1]}
+	attribute=${cmd_options_non_dashed[2]}
+
+	if [ -z "${attribute}" ]; then
+	    # was there a + or - as part of the attribute ?
+	    case ${op} in
+		-*)
+		    attribute=$(echo ${op} | sed 's/^-//')
+		    op="-"
+		    ;;
+		+*)
+		    attribute=$(echo ${op} | sed 's/^+//')
+		    op="+"
+		    ;;
+		*)
+		    attribute=${op}
+		    op=""
+		    ;;
+	    esac
+	fi
+
+	if [ -z "${op}" ] && [ -z "${attribute}" ]; then
+	    # we should output the attributes if they exist
+	    if [ -e ${out_dir}/cube.attributes ]; then
+		cat ${out_dir}/cube.attributes
+	    fi
+	    exit 0
+	fi
+	if [ -z "${op}" ]; then
+	    echo "ERROR: no operation was specified (+ or -)"
+	    exit 1
+	fi
+	if [ -z "${attribute}" ]; then
+	    echo "ERROR: no attribute was specified"
+	    exit 1
+	fi
+
+	## TODO combine this with the get/set code below, since this really
+	## is just a variant that uses append/remove
+	if [ -e ${out_dir}/cube.attributes ]; then
+	    cat ${out_dir}/cube.attributes | grep -q -w ${attribute}
+	    if [ $? -eq 0 ]; then
+		alreadyset=t
+	    fi
+	fi
+	case ${op} in
+	    +)
+		if [ -z "${alreadyset}" ]; then
+		    echo -n "${attribute} " >> ${out_dir}/cube.attributes
+		fi
+		;;
+	    -)
+		if [ -n "${alreadyset}" ]; then
+		    cat ${out_dir}/cube.attributes | sed "s/${attribute}//g" > ${out_dir}/cube.attributes
+		fi
+		;;
+	esac
 	;;
     hook|hook-script)
 	# drop "hook" from the command options, and then output everything
diff --git a/meta-cube/recipes-support/overc-utils/source/cube-ctl b/meta-cube/recipes-support/overc-utils/source/cube-ctl
--- a/meta-cube/recipes-support/overc-utils/source/cube-ctl
+++ b/meta-cube/recipes-support/overc-utils/source/cube-ctl
@@ -35,6 +35,12 @@ commands (and options):
 
        <name>: name of the container to be stopped
 
+ ${0##*/} netprime <name>
+
+    set container as the netprime:
+
+       <name>: name of the container to be the netprime
+
  ${0##*/} stack <container a> <container b>
 
     stack (connect) two containers. This ensures that container a can communicate
@@ -1149,22 +1155,27 @@ case "${cmd}" in
 	    echo "${oci}"
 	else
 	    output=$(mktemp)
-	    echo "name type status" > ${output}
-	    echo "---- ---- ------" >> ${output}
+	    echo "name type status attributes" > ${output}
+	    echo "---- ---- ------ ----------" >> ${output}
 	    for l in ${open_container_running}; do
-		echo "${l} oci running" >> ${output}
+		attributes=$(cube-cfg -n ${l} attribute)
+		echo "${l} oci running ${attributes}" >> ${output}
 	    done
 	    for l in ${open_container_stopped}; do
-		echo "${l} oci stopped" >> ${output}
+		attributes=$(cube-cfg -n ${l} attribute)
+		echo "${l} oci stopped ${attributes}" >> ${output}
 	    done
 	    for l in ${cubes_running}; do
-		echo "${l} cube running" >> ${output}
+		attributes=$(cube-cfg -n ${l} attribute)
+		echo "${l} cube running ${attributes}" >> ${output}
 	    done
 	    for l in ${open_container_available}; do
-		echo "${l} oci available" >> ${output}
+		attributes=$(cube-cfg -n ${l} attribute)
+		echo "${l} oci available ${attributes}" >> ${output}
 	    done
 	    for l in ${cubes_available}; do
-		echo "${l} cube available" >> ${output}
+		attributes=$(cube-cfg -n ${l} attribute)
+		echo "${l} cube available ${attributes}" >> ${output}
 	    done
 	    cat ${output} | column -t
 	    rm ${output}
@@ -1223,6 +1234,24 @@ IFS=$OLDIFS
 	    echo "[ERROR]: provide a container name to see detailed information"
 	    exit 1
 	fi
+	;;
+    netprime)
+	# the second non dashed argument will be the container name
+	container_name=${cmd_options_non_dashed[1]}
+
+	if [ -z "${container_name}" ]; then
+	    echo "[ERROR]: no container name provided"
+	    exit 1
+	fi
+
+	if ! check_is_known_container ${container_name}; then
+	    echo "[ERROR] Container ${container_name} not found, cannot set as netprime."
+	    echo -n "Valid containers are: "
+	    echo ${cubes} ${open_containers}
+	    exit 1
+	fi
+
+	# TODO: runtime switching of the container netprime
 	;;
     stop|pause)
 	graft_binaries_to_essential runc
