networking: reliability fixups and dynamic netprime
This commit brings reliability to the startup of container networking
and a new feature of dynamic netprimes.

It also allows the stacking and redirection of local ports for integration
with orchestration systems.

The significant change here is the fixup of the hooks to manage/control
dhclient integration from essential -> container namespaces. With a custom
dhclient-script, we can now dynamically request IPs without overwriting
essential's resolv.conf (which is sort of important!).

The command 'cube-ctl netprime <container name>' is now functional and
allows the runtime switching of the container responsible for networking
traffic.

As part of that switch, we do not use any of the container's resources
to configure traffic, since we cannot put dependencies on the contents
of the container.

The result is that dns/dhcp is move to a 'vrf' container, which is
currently dom0. But all dns/dhcp still points to the netprime, which
has rules configured to forward the traffic to the VRF.  All containers
in the system are configured to get DNS from the netprime, which
transparently subcontracts it to a container that we can be sure has
the right capabilities and configuration to provide the service.

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>

diff --git a/meta-cube/recipes-support/overc-utils/source/cube-cfg b/meta-cube/recipes-support/overc-utils/source/cube-cfg
--- a/meta-cube/recipes-support/overc-utils/source/cube-cfg
+++ b/meta-cube/recipes-support/overc-utils/source/cube-cfg
@@ -16,7 +16,7 @@ usage()
 {
 cat << EOF
 
- cube-cfg [--clean] <command> <value>
+ ${0##*/} [--clean] <command> <value>
 
  global options:
     
@@ -40,7 +40,7 @@ cat << EOF
 
     mount a directory into the container
 
-       <type>:       optional type of mount. 'bind'
+       <type>:       optional "bind" if a bind mount is to be used
        <name>:<name> source and destination directory
 
  ${0##*/} [-n <container name>] hook <type>:<name>
@@ -53,6 +53,21 @@ cat << EOF
 
        <type>       type of hook: prestart, poststart or poststop
        <name>       full path to the hook
+
+ ${0##*/} link      <container one>:<port> <container two>:<name> [from <ip or "localhost">]
+          link-raw  <container> <command>
+          link-edit <container>
+
+     Modify the linkages betwen containers. The runtime linkage is
+     completed by the 'cube-ctl stack' command.
+
+       link         ensures that the port of container one is linked
+                    (forwarded) to container two.
+       link-raw     exports the passed command to a location where
+                    cube-ctl stack will process it. The correctness of
+                    the command is up to the user
+       link-edit    invokes $EDITOR to manipulated the staged link
+                    commands.
 
  ${0##*/} [-n <container name>] device <type>:<name>:<name>
 
@@ -460,6 +475,7 @@ generate_base_config()
                   --cap-add SYS_RESOURCE \
                   --cap-add NET_ADMIN \
                   --cap-add NET_BROADCAST \
+                  --cap-add SYSLOG \
                   --cap-add SYS_TTY_CONFIG"
 
     app="/sbin/init"
@@ -716,6 +732,28 @@ etcd_fetch()
     fi
 }
 
+# inputs:
+#    1: file to check
+#    2: value we are looking for
+#
+# return:
+#    0: not set
+#    1: is set
+check_isset() {
+    file_to_check=$1
+    shift
+    value_to_check=$@
+
+    if [ -e ${file_to_check} ]; then
+	cat ${file_to_check} | grep -q -w "${value_to_check}"
+	if [ $? -eq 0 ]; then
+	    return 1
+	fi
+    fi
+
+    return 0
+}
+
 etcd_inject()
 {
     local key=$1
@@ -787,21 +825,87 @@ case "${cmd}" in
 	colons=$(echo ${name_temp} | sed -e 's/\(.\)/\1\n/g' | grep : | wc -l)
 	if [ ${colons} -eq 2 ]; then
 	    # we have <type>:<source>:<dest>
+	    type=$(echo ${name_temp} | cut -f1 -d:)
 	    source=$(echo ${name_temp} | cut -f2 -d:)
 	    dest=$(echo ${name_temp} | cut -f3 -d:)
 
-	    # save the mount information for the generation phase
-	    echo "$source:$dest"  >> ${out_dir}/.cube.mount.bind
+	    outfile="${out_dir}/.cube.mount.bind"
+	    op_test="${type}"
 	elif [ ${colons} -eq 1 ]; then
 	    # we have <source>:<dest>
+	    type="standard"
 	    source=$(echo ${name_temp} | cut -f1 -d:)
 	    dest=$(echo ${name_temp} | cut -f2 -d:)
 
-	    # save the mount information for the generation phase
-	    echo "$source:$dest" >> ${out_dir}/.cube.mount
+	    if [ "${source}" == "bind" ]; then
+		# this was really bind mount missing an argument
+		echo "[ERROR]: bind mounts require a source and destination argument"
+		exit 1
+	    fi
+
+	    outfile="${out_dir}/.cube.mount"
+	    op_test="${source}"
 	else
-	    echo "ERROR: Invalid mount specified ${name_temp}"
+	    # we dump the mounts
+	    type=$(echo ${name_temp} | cut -f1 -d:)
+	    if [ "${type}" == "bind" ]; then
+		if [ -e "${out_dir}/.cube.mount.bind" ]; then
+		    cat "${out_dir}/.cube.mount.bind"
+		fi
+	    else
+		if [ -e "${out_dir}/.cube.mount" ]; then
+		    cat "${out_dir}/.cube.mount"
+		fi
+	    fi
+	    exit 0
+	fi
+
+	if [ -z "${source}" ]; then
+	    echo "[ERROR]: no source mount provided"
 	    exit 1
+	fi
+	if [ -z "${dest}" ]; then
+	    echo "[ERROR]: no dest mount provided"
+	    exit 1
+	fi
+
+	if [ -n "${op_test}" ]; then
+	    # was there a + or - as part of the container_a ?
+	    case ${op_test} in
+		-*)
+		    op_test=$(echo ${op_test} | sed 's/^-//')
+		    op="-"
+		    ;;
+		+*)
+		    op_test=$(echo ${op_test} | sed 's/^+//')
+		    op="+"
+		    ;;
+		*)
+		    op="+"
+		    ;;
+	    esac
+	fi
+
+	if [ "${type}" == "standard" ]; then
+	    source="${op_test}"
+	else
+	    type="${op_test}"
+	fi
+
+	if [ "${op}" == "+" ]; then
+	    if [ -n "${verbose}" ]; then
+		echo "[INFO]: adding mount ${source} -> ${dest}"
+	    fi
+
+	    check_isset ${outfile} "${source}:${dest}"
+	    if [ $? -eq 0 ]; then
+		echo "${source}:${dest}" >> ${outfile}
+	    fi
+	else
+	    if [ -n "${verbose}" ]; then
+		echo "[INFO]: removing mount ${source} -> ${dest}"
+	    fi
+	    sed "\|^${source}:${dest}$|d" -i ${outfile}
 	fi
 	;;
     id)
@@ -809,6 +913,96 @@ case "${cmd}" in
 	    cat /etc/machine-id
 	else
 	    echo ""
+	fi
+	;;
+    link)
+	container_a=${cmd_options_non_dashed[1]}
+	container_b=${cmd_options_non_dashed[2]}
+
+	from=${cmd_options_non_dashed[3]}
+	from_ip=${cmd_options_non_dashed[4]}
+
+	container_a_port=$(echo ${container_a} | cut -f2 -d:)
+	container_b_port=$(echo ${container_b} | cut -f2 -d:)
+	container_a=$(echo ${container_a} | cut -f1 -d:)
+	container_b=$(echo ${container_b} | cut -f1 -d:)
+
+	container_name=${container_a}
+	determine_outdir
+
+	if [ -n "${container_a}" ]; then
+	    # was there a + or - as part of the container_a ?
+	    case ${container_a} in
+		-*)
+		    container_a=$(echo ${container_a} | sed 's/^-//')
+		    op="-"
+		    ;;
+		+*)
+		    container_a=$(echo ${container_a} | sed 's/^+//')
+		    op="+"
+		    ;;
+		*)
+		    container_a=${container_a}
+		    op="+"
+		    ;;
+	    esac
+	fi
+
+	if [ -n "${from}" ]; then
+	    if [ -z "${from_ip}" ]; then
+		echo "[ERROR]: 'from' requires a source IP address"
+		exit 1
+	    fi
+
+	    if [ "${from_ip}" == "localhost" ]; then
+		from_ip="127.0.0.1"
+		localhost=t
+	    else
+		source_args="-s ${from_ip}"
+	    fi
+	fi
+
+	if [ -n "${localhost}" ]; then
+	    cmd_1="sysctl -w net.ipv4.conf.all.route_localnet=1"
+	    cmd_2="iptables -A OUTPUT -t nat -p tcp --dport ${container_a_port} -j DNAT --to \${${container_b}_ip}:${container_b_port}"
+	else
+	    cmd_1="iptables -A PREROUTING -t nat -i \${device} -p tcp ${source_args} --dport ${container_a_port} -j DNAT --to \${${container_b}_ip}:${container_b_port}"
+	    cmd_2="iptables -A FORWARD -p tcp -d \${${container_b}_ip}  ${source_args} --dport ${container_b_port} -j ACCEPT"
+	fi
+
+	if [ "${op}" == "+" ]; then
+	    if [ -n "${verbose}" ]; then
+		echo "[INFO]: linking $container_a $container_a_port to $container_b $container_b_port"
+	    fi
+
+	    # TODO. The number of commands needs to be dynamic ..but for now, we'll keep it simple
+	    check_isset ${out_dir}/cube.network.stack $cmd_1
+	    if [ $? -eq 0 ]; then
+		echo "${cmd_1}" >> ${out_dir}/cube.network.stack
+		echo "${cmd_2}" >> ${out_dir}/cube.network.stack
+	    fi
+	else
+	    if [ -n "${verbose}" ]; then
+		echo "[INFO]: removing link from $container_a $container_a_port to $container_b $container_b_port"
+	    fi
+	    sed "\|${cmd_1}|d" -i ${out_dir}/cube.network.stack
+	    sed "\|${cmd_2}|d" -i ${out_dir}/cube.network.stack
+	fi
+	;;
+    link-raw)
+	container=${cmd_options_non_dashed[1]}
+	command=${cmd_options_non_dashed[@]:2}
+	if [ -d "${out_dir}/${container}" ]; then
+	    eval echo ${command} >> ${out_dir}/${container}/cube.network.stack
+	fi
+	;;
+    link-edit)
+	container=${cmd_options_non_dashed[1]}
+	if [ -d "${out_dir}/${container}" ]; then
+	    if [ -z "${EDITOR}" ]; then
+		EDITOR=vim
+	    fi
+	    ${EDITOR} ${out_dir}/${container}/cube.network.stack
 	fi
 	;;
     attribute)
@@ -865,7 +1059,7 @@ case "${cmd}" in
 		;;
 	    -)
 		if [ -n "${alreadyset}" ]; then
-		    cat ${out_dir}/cube.attributes | sed "s/${attribute}//g" > ${out_dir}/cube.attributes
+		    sed "s/${attribute}//g" -i ${out_dir}/cube.attributes
 		fi
 		;;
 	esac
@@ -885,6 +1079,25 @@ case "${cmd}" in
 	    type=$(echo ${name_temp} | cut -f1 -d:)
 	    hookname=$(echo ${name_temp} | cut -f2 -d:)
 
+	    # danger! repeated code, this needs to be unified with the attributes
+	    #         and device code.
+	    if [ -n "${type}" ]; then
+		# was there a + or - as part of the hook type ?
+		case ${type} in
+		    -*)
+			type=$(echo ${type} | sed 's/^-//')
+			op="-"
+			;;
+		    +*)
+			type=$(echo ${type} | sed 's/^+//')
+			op="+"
+			;;
+		    *)
+			op="+"
+		    ;;
+		esac
+	    fi
+
 	    if [ "${cmd}" == "hook-script" ]; then
 		# When we later generate hooks, spaces in the hook definition
 		# are processed as args to the executable. Due to the way
@@ -897,14 +1110,24 @@ case "${cmd}" in
 	    fi
 
 	    if [ "${type}" == "prestart" ]; then
-		echo "${hookname}" >> ${out_dir}/.cube.hooks.prestart
+		outfile="${out_dir}/.cube.hooks.prestart"
 	    elif [ "${type}" == "poststart" ]; then
-		echo "${hookname}" >> ${out_dir}/.cube.hooks.poststart
+		outfile="${out_dir}/.cube.hooks.poststart"
 	    elif [ "${type}" == "poststop" ]; then
-		echo "${hookname}" >> ${out_dir}/.cube.hooks.poststop
+		outfile="${out_dir}/.cube.hooks.poststop"
 	    else
 		echo "ERROR: invalid hook type specified ${type}"
 		exit 1
+	    fi
+
+	    if [ "${op}" == "+" ]; then
+		check_isset ${outfile} ${hookname}
+		if [ $? -eq 0 ]; then
+		    # it isn't already set
+		    echo "${hookname}" >> ${outfile}
+		fi
+	    else
+		sed "\|^${hookname}$|d" -i ${outfile}
 	    fi
 	else
 	    echo "ERROR: Invalid hook specified ${name_temp}"
@@ -933,13 +1156,60 @@ case "${cmd}" in
 	    essential_device=$(echo ${name_temp} | cut -f2 -d:)
 	    container_device=$(echo ${name_temp} | cut -f3 -d:)
 
+	    if [ -n "${device_type}" ]; then
+		# was there a + or - as part of the device ?
+		case ${device_type} in
+		    -*)
+			device_type=$(echo ${device_type} | sed 's/^-//')
+			op="-"
+			;;
+		    +*)
+			device_type=$(echo ${device_type} | sed 's/^+//')
+			op="+"
+			;;
+		    *)
+			op="+"
+			;;
+		esac
+	    fi
+
 	    # save the mount information for the generation phase
 	    case "${device_type}" in
 		network)
-		    echo "$essential_device:$container_device"  >> ${out_dir}/.cube.device.network
+		    check_isset ${out_dir}/.cube.device.network "$essential_device:$container_device"
+		    if [ $? -eq 1 ]; then
+			alreadyset=t
+		    fi
+		    case ${op} in
+			+)
+			    if [ -z "${alreadyset}" ]; then
+				echo "$essential_device:$container_device"  >> ${out_dir}/.cube.device.network
+			    fi
+			    ;;
+			-)
+			    if [ -n "${alreadyset}" ]; then
+				sed "/^${essential_device}:${container_device}$/d" -i ${out_dir}/.cube.device.network
+			    fi
+			    ;;
+		    esac
 		    ;;
 		network-virt)
-		    echo "veth:$essential_device:$container_device"  >> ${out_dir}/.cube.device.network
+		    check_isset ${out_dir}/.cube.device.network "veth:$essential_device:$container_device"
+		    if [ $? -eq 1 ]; then
+			alreadyset=t
+		    fi
+		    case ${op} in
+			+)
+			    if [ -z "${alreadyset}" ]; then
+				echo "veth:$essential_device:$container_device"  >> ${out_dir}/.cube.device.network
+			    fi
+			    ;;
+			-)
+			    if [ -n "${alreadyset}" ]; then
+				sed "/^veth:${essential_device}:${container_device}$/d" -i ${out_dir}/.cube.device.network
+			    fi
+			    ;;
+		    esac
 		    ;;
 		vt)
 		    echo "$essential_device:$container_device"  >> ${out_dir}/.cube.device.vt
@@ -964,7 +1234,7 @@ case "${cmd}" in
 
 	    # - if both are defined, then this is a set
 	    # - if only the var is defined, then this is a get
-	    # - if only the value is defined, it is a clear/delete 
+	    # - if only the value is defined, it is a clear/delete
 	    #   and the value is actually the variable
 	    if [ -n "${var}" ] && [ -n "${value}" ]; then
 		cmd="set"
@@ -979,6 +1249,25 @@ case "${cmd}" in
 	else
 	    var=$(echo ${var_value} | cut -d: -f1)
 	    value=$(echo ${var_value} | cut -d: -f2)
+	fi
+
+	# danger! repeated code, this needs to be unified with the attributes
+	#         and device code.
+	if [ -n "${var}" ]; then
+	    # was there a + or - as part of the variable name ?
+	    case ${var} in
+		-*)
+		    var=$(echo ${var} | sed 's/^-//')
+		    op="-"
+		    ;;
+		+*)
+		    var=$(echo ${var} | sed 's/^+//')
+		    op="+"
+		    ;;
+		*)
+		    op="+"
+		    ;;
+	    esac
 	fi
 
 	if [ -z "${CONFIG_MAP[$var]}" ]; then
@@ -1014,12 +1303,17 @@ case "${cmd}" in
 		if [ -f ${out_dir}/${db_var} ]; then
 		    previous=$(cat ${out_dir}/${db_var})
 		fi
-		if [ -n "${prepend}" ]; then
-		    echo "${value} ${previous}" > ${out_dir}/${db_var}
-		elif [ -n "${append}" ]; then
-		    echo "${previous} ${value}" > ${out_dir}/${db_var}
+
+		if [ "${op}" == "+" ]; then
+		    if [ -n "${prepend}" ]; then
+			echo "${value} ${previous}" > ${out_dir}/${db_var}
+		    elif [ -n "${append}" ]; then
+			echo "${previous} ${value}" > ${out_dir}/${db_var}
+		    else
+			echo "${value}" > ${out_dir}/${db_var}
+		    fi
 		else
-		    echo "${value}" > ${out_dir}/${db_var}
+		    sed "s%${value} *%%g" -i ${out_dir}/${db_var}
 		fi
 	    else
 		if [ -e "${out_dir}/${db_var}" ]; then
diff --git a/meta-cube/recipes-support/overc-utils/source/cube-ctl b/meta-cube/recipes-support/overc-utils/source/cube-ctl
--- a/meta-cube/recipes-support/overc-utils/source/cube-ctl
+++ b/meta-cube/recipes-support/overc-utils/source/cube-ctl
@@ -17,9 +17,9 @@ usage()
 {
 cat << EOF
 
-  cube-ctl <options> <cmd>
+ ${0##*/} <options> <cmd>
 
-commands (and options):
+ commands (and options):
 
  ${0##*/} start [--peer] [--nested] [--auto] <name>
 
@@ -44,10 +44,10 @@ commands (and options):
  ${0##*/} stack <container a> <container b>
 
     stack (connect) two containers. This ensures that container a can communicate
-    with container b.
+    with container b via a defined port.
 
-       <container a>: name of the first container to be stacked
-       <container b>: name of the second container to be stacked
+       <container a>: name of the first container and port to be stacked
+       <container b>: name of the second container and port to be stacked
 
  ${0##*/} store <container> <location>
 
@@ -132,7 +132,7 @@ DEFAULT_SUBUID=800000
 
 while [ $# -gt 0 ]; do
     case "$1" in
-	-v) verbose=t
+	-v|--verbose) verbose=t
             ;;
         --peer)
 	    peer=t
@@ -253,6 +253,11 @@ fi
 am_i_a_container
 if [ $? -eq 1 ]; then
     we_are_a_container=t
+fi
+
+if [ -z "${we_are_dom0}" ] && [ -n "${we_are_a_container}" ]; then
+    cube-cmd cube-ctl ${raw_command}
+    exit $?
 fi
 
 # make an array from whatever was non-dashed
@@ -610,6 +615,37 @@ spinner()
         printf "\b\b\b\b\b\b"
     done
     printf "    \b\b\b\b"
+}
+
+get_container_ips() {
+    local container_name=$1
+
+    dpid=$(cat ${container_dir}/${container_name}/.cube.pid)
+    ip_ext=$(cube-cmd nsenter -t ${dpid} -n ip route get 8.8.8.8 | tr -s ' ' | cut -d' ' -f7)
+    ip_int=$(cube-cmd nsenter -t ${dpid} -n ip route get 192.168.42.254 | tr -s ' ' | cut -d' ' -f5)
+
+    if [ "${ip_ext}" == "${ip_int}" ]; then
+	echo ${ip_ext}
+    else
+	echo "${ip_int},${ip_ext}"
+    fi
+}
+
+get_container_type() {
+    local container_name=$1
+
+    if [ -e "${container_dir}/${container_name}/pflask.cmd" ]; then
+	echo cube
+    else
+	echo oci
+    fi
+}
+
+get_container_attributes() {
+    local container_name=$1
+    local attributes=$(cube-cfg -n ${container_name} attribute | sed 's/^ *$//')
+
+    echo ${attributes}
 }
 
 #
@@ -1062,7 +1098,66 @@ case "${cmd}" in
 	fi
 	;;
     stack)
-	# TODO
+	container_name=${cmd_options_non_dashed[1]}
+	if [ -e ${container_dir}/${container_name}/cube.network.stack ]; then
+	    if [ -n "${verbose}" ]; then
+		echo "[INFO]: network stack detected, excuting commands"
+	    fi
+	    (
+		cd ${container_dir}/${container_name}
+
+		# we need to resolve an variable references. Currently this
+		# is IPS and devices
+		vars=$(cat cube.network.stack | grep -o -E '\${[A-Za-z0-9])*[A-Za-z](_?[A-Za-z0-9])*}' | uniq)
+		spid=$(cat .cube.pid)
+
+		for v in $vars; do
+		    case $v in
+			*device*)
+			    netdevs=$(cat .cube.device.network)
+			    for n in ${netdevs}; do
+				echo ${n} | grep -q veth
+				if [ $? -ne 0 ]; then
+				    # we have a real device. Last one wins.
+				    device=$(echo ${n} | cut -f1 -d:)
+				fi
+			    done
+			    ;;
+			*_ip*)
+			    cname=$(echo $v | sed -r 's/.*\$\{(.+)_.*\}.*/\1/')
+			    # this doesn't actually go out on the wire, but it is the best
+			    # way to get the IP of the interface in the container. If we need
+			    # something besides the external route for the IP, this can be
+			    # tweaked.
+			    dpid=$(cat ${container_dir}/${cname}/.cube.pid)
+			    ip=$(cube-cmd nsenter -t ${dpid} -n ip route get 8.8.8.8 | tr -s ' ' | cut -d' ' -f7)
+			    eval ${cname}_ip=${ip}
+			    ;;
+		    esac
+		done
+
+		# read the commands, resolve variables and execute them in the proper
+		# namespace
+		while read -u 10 cmd; do
+		    # With the variable creation above, these will echo without any unknown
+		    # variables .. if there are remaining vars, it is an error.
+		    echo ${cmd} | grep -q iptables
+		    if [ $? -eq 0 ]; then
+			cmd_check=$(echo ${cmd} | sed 's/iptables -A/iptables -C/')
+			eval cube-cmd nsenter -t ${spid} -n --preserve-credentials "$cmd_check" 2> /dev/null
+		    else
+			# just so $? can run the command without a check :D
+			false
+		    fi
+		    if [ $? -ne 0 ]; then
+			if [ -n "${verbose}" ]; then
+			    echo "INFO: nsenter -t ${spid} -n --preserve-credentials \"$cmd\""
+			fi
+			eval cube-cmd nsenter -t ${spid} -n --preserve-credentials "$cmd"
+		    fi
+		done 10<cube.network.stack
+	    )
+	fi
 	;;
     del|delete|remove)
 	graft_binaries_to_essential runc
@@ -1086,22 +1181,25 @@ case "${cmd}" in
 	    echo ${cubes} ${open_containers} ${open_container_available}
 	    exit 1
 	fi
-	echo "[INFO] deleting container ${container_name}"
 
 	if [ -n "${container_is_a_cube}" ]; then
 	    # nothing to do at the moment
 	    true
 	fi
 	if [ -n "${container_is_a_oci}" ]; then
-	    # TODO: the container state needs to be tracked better, and only
-	    #       do this if it is running
-	    cube-cmd ${runc_essential} delete ${container_name} 2> /dev/null
-	    if [ -d "${out_dir}/${container_name}" ]; then
-		echo "[INFO] removing container source .."
-		rm -rf "${out_dir}/${container_name}"
+	    echo ${open_container_running} | grep -q ${container_name}
+	    if [ $? -ne 0 ]; then
+		echo "[INFO] deleting container ${container_name}"
+		cube-cmd ${runc_essential} delete ${container_name} 2> /dev/null
+		if [ -d "${out_dir}/${container_name}" ]; then
+		    echo "[INFO] removing container source .."
+		    rm -rf "${out_dir}/${container_name}"
+		fi
+		machine=$(cube-cfg id)
+		cube-cfg set overc/$machine/oci/${container_name}/:
+	    else
+		echo "[INFO] container ${container_name} is running, it must be stopped before deleting"
 	    fi
-	    machine=$(cube-cfg id)
-	    cube-cfg set overc/$machine/oci/${container}/:
 	fi
 	;;
     start)
@@ -1163,12 +1261,12 @@ case "${cmd}" in
 			fi
 		    )
 		fi
-	    else
-		if [ -e "${container_dir}/${container}/pflask.cmd" ]; then
-		    rm -f /tmp/${container}-console
-		    dtach -n /tmp/${container}-console ${container_dir}/${container}/pflask.cmd
-		fi
 	    fi
+	done
+
+	# once everything has started, look for stacked network commands
+	for container in ${container_names}; do
+	    cube-ctl stack ${container}
 	done
 	;;
     status|list)
@@ -1186,27 +1284,44 @@ case "${cmd}" in
 	    echo "${oci}"
 	else
 	    output=$(mktemp)
-	    echo "name type status attributes" > ${output}
-	    echo "---- ---- ------ ----------" >> ${output}
+	    echo "name type status attributes addresses" > ${output}
+	    echo "---- ---- ------ ---------- ---------" >> ${output}
 	    for l in ${open_container_running}; do
 		attributes=$(cube-cfg -n ${l} attribute)
-		echo "${l} oci running ${attributes}" >> ${output}
+		if [ -z "${attributes}" ]; then
+		    attributes="--"
+		fi
+		ip=$(get_container_ips ${l})
+		echo "${l} oci running ${attributes} ${ip}" >> ${output}
 	    done
 	    for l in ${open_container_stopped}; do
-		attributes=$(cube-cfg -n ${l} attribute)
-		echo "${l} oci stopped ${attributes}" >> ${output}
+		attributes=$(get_container_attributes ${l})
+		if [ -z "${attributes}" ]; then
+		    attributes="--"
+		fi
+		echo "${l} oci stopped ${attributes} --" >> ${output}
 	    done
 	    for l in ${cubes_running}; do
-		attributes=$(cube-cfg -n ${l} attribute)
-		echo "${l} cube running ${attributes}" >> ${output}
+		ip=$(get_container_ips ${l})
+		attributes=$(get_container_attributes ${l})
+		if [ -z "${attributes}" ]; then
+		    attributes="--"
+		fi
+		echo "${l} cube running ${attributes} ${ip}" >> ${output}
 	    done
 	    for l in ${open_container_available}; do
-		attributes=$(cube-cfg -n ${l} attribute)
-		echo "${l} oci available ${attributes}" >> ${output}
+		attributes=$(get_container_attributes ${l})
+		if [ -z "${attributes}" ]; then
+		    attributes="--"
+		fi
+		echo "${l} oci available ${attributes} --" >> ${output}
 	    done
 	    for l in ${cubes_available}; do
-		attributes=$(cube-cfg -n ${l} attribute)
-		echo "${l} cube available ${attributes}" >> ${output}
+		attributes=$(get_container_attributes ${l})
+		if [ -z "${attributes}" ]; then
+		    attributes="--"
+		fi
+		echo "${l} cube available ${attributes} --" >> ${output}
 	    done
 	    cat ${output} | column -t
 	    rm ${output}
@@ -1282,14 +1397,111 @@ IFS=$OLDIFS
 	    exit 1
 	fi
 
-	# TODO: runtime switching of the container netprime
+	attributes=$(${SBINDIR}/cube-cfg -n ${container_name} attribute)
+	echo ${attributes} | grep -q netprime
+	if [ $? -eq 0 ]; then
+	    echo "[INFO]: container \"${container_name}\" is already the netprime"
+	    exit 0
+	fi
+
+	if [ -z "${out_dir}" ]; then
+	    out_dir="${container_dir}"
+	fi
+
+	# TODO: this could be an etcd lookup, not this ...
+        containers_available=$(ls ${out_dir})
+	for c in ${containers_available}; do
+	    attributes=$(${SBINDIR}/cube-cfg -n ${c} attribute)
+	    echo ${attributes} | grep -q netprime
+	    if [ $? -eq 0 ]; then
+		network_prime_old=${c}
+	    fi
+	done
+	network_prime=${container_name}
+
+	# step 1: stop the old network prime (if it exists)
+	if [ -n "${network_prime_old}" ]; then
+	    (
+		if [ -n "${verbose}" ]; then
+		    echo "[INFO]: stopping current netprime (${network_prime_old})"
+		fi
+		cd ${out_dir}/${network_prime_old}
+		# TODO: how to detect if we are the installer and not run this ?
+		${SBINDIR}/cube-ctl stop ${network_prime_old}
+	    )
+	fi
+
+	# step 2: configure the new network prime
+	(
+	    if [ -n "${verbose}" ]; then
+		echo "[INFO]: configuring new netprime (${network_prime})"
+	    fi
+	    cd ${out_dir}/${network_prime}
+
+	    ${SBINDIR}/cube-cfg set cube.network.type:static
+	    ${SBINDIR}/cube-cfg --prepend set cube.network.ip:192.168.42.1/24
+
+	    devs=$(${SBINDIR}/cube-cfg -o ${out_dir}/${network_prime_old} device network)
+	    for d in ${devs}; do
+		${SBINDIR}/cube-cfg device network:$d
+	    done
+
+	    ${SBINDIR}/cube-cfg attribute +netprime
+
+	    # ensure that etcd (on dom0) is accessible
+	    ${SBINDIR}/cube-cfg link ${network_prime}:2379 dom0:2379
+
+	    type=$(get_container_type ${network_prime})
+	    if [ "${type}" == "oci" ]; then
+		${SBINDIR}/cube-cfg hook-script poststart:/usr/libexec/cube/hooks.d/cube-netconfig netprime \$\(cat\)
+		#${SBINDIR}/cube-cfg hook-script poststart:/usr/libexec/cube/hooks.d/cube-netconfig vrf \$\(cat\)
+	    else
+		${SBINDIR}/cube-cfg hook-script poststart:/usr/libexec/cube/hooks.d/cube-netconfig netprime /opt/container/${network_prime}
+		#${SBINDIR}/cube-cfg hook-script poststart:/usr/libexec/cube/hooks.d/cube-netconfig vrf /opt/container/${network_prime}	
+	    fi
+
+	    ${SBINDIR}/cube-cfg gen ${network_prime}:$type
+	)
+
+	# step 3: reconfigure the old network prime (if it exists)
+	# TODO: there could be an option to skip this (so you could switch back without needing
+	#       to rerun the netprime command
+	if [ -n "${network_prime_old}" ]; then
+	    (
+		if [ -n "${verbose}" ]; then
+		    echo "[INFO]: reconfiging previous netprime"
+		fi
+		# TODO: this won't work if called from the installer, the dir for containers
+		#       needs to vary and we can't stop the container
+		cd ${out_dir}/${network_prime_old}
+		${SBINDIR}/cube-cfg attribute -netprime
+		${SBINDIR}/cube-cfg set cube.network.type:dynamic
+		${SBINDIR}/cube-cfg set -cube.network.ip:192.168.42.1/24
+
+		devs=$(${SBINDIR}/cube-cfg -o ${out_dir}/${network_prime_old} device network)
+		for d in ${devs}; do
+		    echo "${d}" | grep -q veth
+		    # drop any h/w devices that were passed through, leave the veth
+		    if [ $? -ne 0 ]; then
+			${SBINDIR}/cube-cfg device -network:$d
+		    fi
+		done
+
+		# remove the old hook and etcd port forward
+		${SBINDIR}/cube-cfg hook-script -poststart:/usr/libexec/cube/hooks.d/cube-netconfig netprime \$\(cat\)
+		${SBINDIR}/cube-cfg link -${network_prime}:2379 dom0:2379
+
+		type=$(get_container_type ${network_prime})
+		${SBINDIR}/cube-cfg gen ${network_prime}:type
+	    )
+	fi
 	;;
     stop|pause)
 	graft_binaries_to_essential runc
 	if [ -f "/var/lib/cube/essential/sbin/runc" ]; then
 	    runc_essential="/var/lib/cube/essential/sbin/runc"
 	else
-	    echo "ERROR: unable to execute runc on essential"
+	    echo "[ERROR]: unable to execute runc on essential"
 	    exit 1
 	fi
 
@@ -1302,23 +1514,28 @@ IFS=$OLDIFS
 	fi
 
 	if ! check_is_known_container ${container_name}; then
-	    echo "[ERROR] Container ${container_name} not found, cannot stop."
+	    echo "[ERROR]: container ${container_name} not found, cannot stop."
 	    echo -n "Valid containers are: "
 	    echo ${cubes} ${open_containers}
 	    exit 1
 	fi
-	echo "[INFO] stopping container ${container_name}"
 
 	if [ -n "${container_is_a_cube}" ]; then
 	    cube-cmd machinectl stop ${container_name}
 	fi
 	if [ -n "${container_is_a_oci}" ]; then
-	    cube-cmd ${runc_essential} kill ${container_name} KILL
-	    if [ "${cmd}" == "stop" ]; then
-		cube-cmd ${runc_essential} delete ${container_name}
+	    echo ${open_container_running} | grep -q ${container_name}
+	    if [ $? -eq 0 ]; then
+		echo "[INFO] stopping container ${container_name}"
+		cube-cmd ${runc_essential} kill ${container_name} KILL
+		if [ "${cmd}" == "stop" ]; then
+		    cube-cmd ${runc_essential} delete ${container_name}
+		fi
+		machine=$(cube-cfg id)
+		cube-cfg set overc/$machine/oci/${container_name}/status:inactive
+	    else
+		echo "[INFO]: container ${container_name} is not running, cannot stop"
 	    fi
-	    machine=$(cube-cfg id)
-	    cube-cfg set overc/$machine/oci/${container_name}/status:inactive
 	fi
 	;;
     exec)
