cube-ctl/console: add explicit error message when invoked from essential
Many of the cube* commands require a command server. When logged into
essential, there is no monitoring server (since we are the root of the system)
and hence the commands don't work.

Commands should either be directly invoked (ie. lxc*) or better, the
control domain used (dom0).

To make this obvious/explicit, we can detect that we are not in a container
and dump an explanation.

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>

diff --git a/meta-cube/recipes-support/overc-utils/source/cube-console b/meta-cube/recipes-support/overc-utils/source/cube-console
--- a/meta-cube/recipes-support/overc-utils/source/cube-console
+++ b/meta-cube/recipes-support/overc-utils/source/cube-console
@@ -59,6 +59,20 @@ if [ -d "/host/proc" ]; then
     we_are_dom0=t
 fi
 
+# returns 1 if we are container, 0 otherwise                                                                                                                                 
+function am_i_a_container()
+{   
+    # the 3rd field is the hierarchy. If we are the host, the hierarchy                                                                                                      
+    # is always "/" or "/init.scope". Otherwise, we are a container.                                                                                                         
+    local archy=`cat /proc/1/cgroup | cut -d: -f3 | head -1`
+    if [ "${archy}" = "/" ] || [ "${archy}" = "/init.scope" ]; then
+        return 0
+    fi
+
+    return 1
+}
+
+
 function wait_for_files()
 {
     local wait_count=${1:-200} # 200 is the default
@@ -219,5 +233,13 @@ function enter_console
 	    ;;
     esac
 }
+
+am_i_a_container
+if [ $? -eq 0 ]; then
+    echo "ERROR: host detected, cube-console only works in a monitored container."
+    echo "       Commands must be directly invoked in essential, control functions"
+    echo "       via the control domain."
+    exit 1
+fi
 
 enter_console $1
diff --git a/meta-cube/recipes-support/overc-utils/source/cube-ctl b/meta-cube/recipes-support/overc-utils/source/cube-ctl
--- a/meta-cube/recipes-support/overc-utils/source/cube-ctl
+++ b/meta-cube/recipes-support/overc-utils/source/cube-ctl
@@ -101,6 +101,23 @@ done
 
 dom0ctl="/opt/dom0-contctl/dom0_contctl"
 
+# returns 1 if we are container, 0 otherwise                                                                                                                                $
+function am_i_a_container()
+{
+    # the 3rd field is the hierarchy. If we are the host, the hierarchy                                                                                                     $
+    # is always "/" or "/init.scope". Otherwise, we are a container.                                                                                                        $
+    local archy=`cat /proc/1/cgroup | cut -d: -f3 | head -1`
+    if [ "${archy}" = "/" ] || [ "${archy}" = "/init.scope" ]; then
+        return 0
+    fi
+
+    return 1
+}
+
+if [ -d "/host/proc" ]; then
+    we_are_dom0=t
+fi
+
 # make an array from whatever was non-dashed
 cmd_options_non_dashed=(${non_dashed})
 
@@ -124,6 +141,14 @@ check_if_present()
     fi
     return 1
 }
+
+am_i_a_container
+if [ $? -eq 0 ]; then
+    echo "ERROR: host detected, cube-ctl only works in a monitored container."
+    echo "       Commands must be directly invoked in essential, control functions"
+    echo "       via the control domain."
+    exit 1
+fi
 
 case "${cmd}" in
     start)
