c3 list: make container listing 'smarter'
It was possible to issue an invalid set command, and create a container
manager setting in the current working directory. This incorrectly placed
setting, could then be picked up by subsequent 'get' commands, which
allowed invalid containers to end up in the container listing.

To fix this, we tighten up the out_dir detection code to ensure that
/opt/container/<foo> actually exists, and also, to not care if config.json
exists.

Additionally, we also add a new container state of "invalid" if an
incorrect container manager is configured.

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>

diff --git a/meta-cube/recipes-support/overc-utils/source/cube-cfg b/meta-cube/recipes-support/overc-utils/source/cube-cfg
--- a/meta-cube/recipes-support/overc-utils/source/cube-cfg
+++ b/meta-cube/recipes-support/overc-utils/source/cube-cfg
@@ -365,10 +365,19 @@ determine_outdir()
 	if [ -n "${container_name}" ]; then
 	    if [ -d "/opt/container/${container_name}" ]; then
 		# but only if we have a config.json, should this actually become
-		# our outdir
-		if [ -f "/opt/container/${container_name}/config.json" ]; then
+		# our outdir.
+
+		# Jan 2018: Temporarily disabling this extra check, since we
+		# are now erroring if the container isn't in /opt/container
+		# .. but there used to be errors if we didn't have this
+		# check, so keeping this around to see if they pop back out.
+
+		#if [ -f "/opt/container/${container_name}/config.json" ]; then
 		    out_dir="/opt/container/${container_name}"
-		fi
+		#fi
+	    else
+		echo "[ERROR]: container \"${container_name}\" has no valid directory"
+		exit 1
 	    fi
 	fi
     fi
@@ -1938,7 +1947,6 @@ case "${cmd}" in
 		etcd_fetch ${var}
 	    fi
 	else
-
 	    if [ "${cmd}" = "set" ]; then
 		outvar=${out_dir}/${db_var}
 		if [ -n "${runonce}" ]; then
diff --git a/meta-cube/recipes-support/overc-utils/source/cube-ctl b/meta-cube/recipes-support/overc-utils/source/cube-ctl
--- a/meta-cube/recipes-support/overc-utils/source/cube-ctl
+++ b/meta-cube/recipes-support/overc-utils/source/cube-ctl
@@ -880,6 +880,11 @@ get_container_state() {
 		    # this is OCI output, but the container is not active
 		    echo "available"
 		fi
+		echo "${state}" | grep -q "ailed to execute"
+		if [ $? -eq 0 ]; then
+		    # the container manager wasn't found, mark as invalid
+		    echo "invalid"
+		fi
 	    fi
 	fi
     fi
