cube-ctl: check if a container is known before attempting to stop it
Currently if you issue the 'cube-ctl stop' command and provide an
invalid container name you will get a failure exit code but no
indication as to why the command failed. This is inconsistent with
'cube-ctl del' where we do check the validity of the container name
first.

Put the code used by 'cube-ctl del' to check the validity of the
container name into a function called check_is_known_container() and
use this for 'del' as well as 'stop' to provide the user with useful
feedback.

NOTE: the logic used in 'del' has changed some but as far as I can
tell the updated logic I have used here is more complete. ie. It
properly handles the case where 'i_am_dom0' is false.

Signed-off-by: Mark Asselstine <mark.asselstine@windriver.com>

diff --git a/meta-cube/recipes-support/overc-utils/source/cube-ctl b/meta-cube/recipes-support/overc-utils/source/cube-ctl
--- a/meta-cube/recipes-support/overc-utils/source/cube-ctl
+++ b/meta-cube/recipes-support/overc-utils/source/cube-ctl
@@ -184,6 +184,28 @@ check_if_present()
     return 1
 }
 
+# Check if the passed string matches any known container names
+# return false (1) if unknown, true (0) if known
+# additionally sets the global ${containers}
+check_is_known_container()
+{
+    container_name=$1
+
+    if [ -n "${i_am_dom0}" ]; then
+	containers="`cube-cmd lxc-ls`"
+	if [ -n "${containers}" ]; then
+	    echo ${containers} | grep -q -w ${container_name}
+	    if [ $? -ne 0 ]; then
+		return 1
+	    fi
+	fi
+    else
+	return 1
+    fi
+
+    return 0
+}
+
 am_i_a_container
 if [ $? -eq 0 ]; then
     echo "ERROR: host detected, cube-ctl only works in a monitored container."
@@ -236,18 +258,11 @@ case "${cmd}" in
 	# the second non dashed argument will be the container name
 	container_name=${cmd_options_non_dashed[1]}
 
-	if [ -n "${i_am_dom0}" ]; then
-	    containers="`cube-cmd lxc-ls`"
-	fi
-
-	if [ -n "${containers}" ]; then
-	    echo ${containers} | grep -q -w ${container_name}
-	    if [ $? -ne 0 ]; then
-		echo "[ERROR] Container ${container_name} not found, cannot remove."
-		echo -n "Valid containers are: "
-		echo ${containers}
-		exit 1
-	    fi
+	if ! check_is_known_container ${container_name}; then
+	    echo "[ERROR] Container ${container_name} not found, cannot remove."
+	    echo -n "Valid containers are: "
+	    echo ${containers}
+	    exit 1
 	fi
 
 	echo "[INFO] stopping container ${container_name}"
@@ -296,6 +311,14 @@ case "${cmd}" in
 
 	# the second non dashed argument will be the container name
 	container_name=${cmd_options_non_dashed[1]}
+
+	if ! check_is_known_container ${container_name}; then
+	    echo "[ERROR] Container ${container_name} not found, cannot stop."
+	    echo -n "Valid containers are: "
+	    echo ${containers}
+	    exit 1
+	fi
+	echo "[INFO] stopping container ${container_name}"
 	${dom0ctl} stop -n ${container_name}
 	;;
     exec)
