c3-cfg: localhost data links + xauth capabilities
To finish the enablement of cross-X in containers, we need two more
features:

  - The ability to link data directories from host -> container
  - The ability to xauthenticate a container

This commit combines the two features as a unit, to allow the following
scenario to work:

  % c3 add docker://jbonds/xterm

  % c3 stop cube-desktop

  % c3-cfg -v link localhost:.XIM-unix cube-desktop:/tmp/.XIM-unix
  % c3-cfg -v link localhost:.Test-unix cube-desktop:/tmp/.Test-unix
  % c3-cfg -v link localhost:.ICE-unix cube-desktop:/tmp/.ICE-unix
  % c3-cfg -v link localhost:.font-unix cube-desktop:/tmp/.font-unix
  % c3-cfg -v link localhost:.X11-unix cube-desktop:/tmp/.X11-unix

  % c3-cfg -v link localhost:.XIM-unix xterm:/tmp/.XIM-unix
  % c3-cfg -v link localhost:.Test-unix xterm:/tmp/.Test-unix
  % c3-cfg -v link localhost:.ICE-unix xterm:/tmp/.ICE-unix
  % c3-cfg -v link localhost:.font-unix xterm:/tmp/.font-unix
  % c3-cfg -v link localhost:.X11-unix xterm:/tmp/.X11-unix
  % c3-cfg -n xterm set cube.env:DISPLAY=:0

  % c3-cfg gen cube-desktop
  % c3-cfg gen xterm

  % c3 start cube-desktop
  # <log into X session as appropriate>

  % c3-cfg auth X:cube-desktop:xterm
  % c3 start xterm

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>

diff --git a/meta-cube/recipes-support/overc-utils/source/cube-cfg b/meta-cube/recipes-support/overc-utils/source/cube-cfg
--- a/meta-cube/recipes-support/overc-utils/source/cube-cfg
+++ b/meta-cube/recipes-support/overc-utils/source/cube-cfg
@@ -86,21 +86,29 @@ EOF
 usage_auth()
 {
 cat <<EOF
- ${0##*/} auth <type>:<userid>:<password>
+ ${0##*/} auth <type>:<auth parm 1>:<auth parm 2>
 
-    Create an authorization
+    Create an authorization.
 
-       <type>:       Type of registry: "docker" or "cube"
-       <userid>:
-       <password>
+          <type>:  Type: "docker", "cube" or "X"
 
-    Authorization will be stored in the user's home directory .overc/auths.json
+    If type is "docker" or "cube", the parameters are
 
-    If a container name is provided via [-n <name>], then the authorization is
-    stored per-container in the same "auths.json" file.
+             <userid>
+             <password>
 
-    if only <type> is provided, then the default authorization for that registry
-    type will be returned.
+          Authorization will be stored in the user's home directory .overc/auths.json
+
+          If a container name is provided via [-n <name>], then the authorization is
+          stored per-container in the same "auths.json" file.
+
+         if only <type> is provided, then the default authorization for that registry
+         type will be returned.
+
+   If type is "X", the parameters are:
+
+          <container a>: The container running the X server
+          <container b>: The container to grant access to container A's X session
 
 EOF
 }
@@ -364,6 +372,10 @@ determine_outdir()
     # the out_dir explicitly
     if [ "${out_dir}" == "./" ]; then
 	if [ -n "${container_name}" ]; then
+	    if [ "${container_name}" = "localhost" ] ||
+		   [ "${container_name}" = "host" ]; then
+		return
+	    fi
 	    echo "${PWD}" | grep -q -w ${container_name}
 	    if [ $? -eq 0 ]; then
 		# we are in a directory that contains the container name, leave
@@ -1282,16 +1294,45 @@ set_authorization()
     local auth_file="auths.json"
     local auth_dir="~/.overc/"
 
-    eval auth_dir=${auth_dir}
-    if [ -n "${container_name}" ]; then
-	auth_dir="/opt/container/${container_name}"
-    fi
-    if [ "${auth_type}" == "docker" ]; then
-	if [ ! -d "${auth_dir}" ]; then
-	    mkdir -p "${auth_dir}"
+    if [ "${auth_type}" = "X" ]; then
+	# if we are doing an X auth, the auth_user is the container running the X session
+	# and the auth_password is the container to which we are granting access
+	if [ ! -e "/opt/container/${auth_user}/rootfs/usr/bin/xauth" ]; then
+	    echo "[ERROR]: container ${auth_user} does not have an xauth binary"
+	    exit 1
+	fi
+	if [ ! -e "/opt/container/${auth_user}/rootfs/root/.Xauthority" ]; then
+	    echo "[ERROR]: container ${auth_user} does not have a .Xauthority file, is X running (and active) ?"
+	    exit 1
+	fi
+	if [ ! -d "/opt/container/${auth_password}/rootfs/root/" ]; then
+	    echo "[ERROR]: container ${auth_password} does not have an root/ directory for .Xauthority"
+	    exit 1
 	fi
 
-	if [ ! -f "${auth_dir}/${auth_file}" ]; then
+	# do the xauth magic
+	if [ -n "${verbose}" ]; then
+	    echo "[INFO]: granting Xauth to ${auth_user} to ${auth_password} via:"
+	    echo  "   LD_LIBRARY_PATH=/opt/container/${auth_user}/rootfs/usr/lib64  /opt/container/${auth_user}/rootfs/usr/bin/xauth -f /opt/container/${auth_password}/rootfs/root/.Xauthority add \`LD_LIBRARY_PATH=/opt/container/${auth_user}/rootfs/usr/lib64 /opt/container/${auth_user}/rootfs/usr/bin/xauth -f /opt/container/${auth_user}/rootfs/root/.Xauthority list | grep ${auth_user} |sed -e \"s/${auth_user}/${auth_password}/\"\`"
+	fi
+
+	LD_LIBRARY_PATH=/opt/container/${auth_user}/rootfs/usr/lib64 \
+		        /opt/container/${auth_user}/rootfs/usr/bin/xauth \
+		        -f /opt/container/${auth_password}/rootfs/root/.Xauthority add \
+			`LD_LIBRARY_PATH=/opt/container/${auth_user}/rootfs/usr/lib64 /opt/container/${auth_user}/rootfs/usr/bin/xauth \
+                             -f /opt/container/${auth_user}/rootfs/root/.Xauthority list | grep ${auth_user} |sed -e "s/${auth_user}/${auth_password}/"` 2> /dev/null
+    else
+	# expands "~"
+	eval auth_dir=${auth_dir}
+	if [ -n "${container_name}" ]; then
+	    auth_dir="/opt/container/${container_name}"
+	fi
+	if [ "${auth_type}" == "docker" ]; then
+	    if [ ! -d "${auth_dir}" ]; then
+		mkdir -p "${auth_dir}"
+	    fi
+
+	    if [ ! -f "${auth_dir}/${auth_file}" ]; then
 cat > ${auth_dir}/${auth_file} <<EOF
 	{
 	    "auths": {
@@ -1304,13 +1345,14 @@ cat > ${auth_dir}/${auth_file} <<EOF
 	    }
 	}
 EOF
+	    fi
+
+            auth_string=$(echo "${auth_user}:${auth_password}" | base64)
+	    auth_string="${auth_string}="
+
+	    jq ".[\"auths\"][\"https://index.docker.io/v1/\"][\"auth\"] = \"${auth_string}\"" ${auth_dir}/${auth_file} > ${auth_dir}/${auth_file}.new 
+	    mv ${auth_dir}/${auth_file}.new ${auth_dir}/${auth_file}
 	fi
-
-        auth_string=$(echo "${auth_user}:${auth_password}" | base64)
-	auth_string="${auth_string}="
-
-	jq ".[\"auths\"][\"https://index.docker.io/v1/\"][\"auth\"] = \"${auth_string}\"" ${auth_dir}/${auth_file} > ${auth_dir}/${auth_file}.new 
-	mv ${auth_dir}/${auth_file}.new ${auth_dir}/${auth_file}
     fi
 }
 
@@ -1346,36 +1388,38 @@ case "${cmd}" in
 	    auth_user=$(echo ${auth_string} | cut -f2 -d:)
 	    auth_password=$(echo ${auth_string} | cut -f3 -d:)
 
-	    if [ -z "${auth_user}" ]; then
-		echo -n "${auth_type} user: "
-		read auth_user
-	    fi
-	    if [ -z "${auth_password}" ]; then
-
-		# fancy reading and echo'ing of * for each char
-		tty -s
-		if [ $? -eq 0 ]; then
-		    echo -n "${auth_type} password: "
+	    if [ "${auth_type}" != "X" ]; then
+		if [ -z "${auth_user}" ]; then
+		    echo -n "${auth_type} user: "
+		    read auth_user
 		fi
-		while IFS= read -p "$prompt" -r -s -n 1 char
-		do
-		    # Enter - accept password
-		    if [[ $char == $'\0' ]] ; then
-			break
+		if [ -z "${auth_password}" ]; then
+
+		    # fancy reading and echo'ing of * for each char
+		    tty -s
+		    if [ $? -eq 0 ]; then
+			echo -n "${auth_type} password: "
 		    fi
-		    # Backspace
-		    if [[ $char == $'\177' ]] ; then
-			prompt=$'\b \b'
-			password="${password%?}"
-		    else
-			prompt='*'
-			password+="$char"
+		    while IFS= read -p "$prompt" -r -s -n 1 char
+		    do
+			# Enter - accept password
+			if [[ $char == $'\0' ]] ; then
+			    break
+			fi
+			# Backspace
+			if [[ $char == $'\177' ]] ; then
+			    prompt=$'\b \b'
+			    password="${password%?}"
+			else
+			    prompt='*'
+			    password+="$char"
+			fi
+		    done
+		    auth_password=${password}
+		    tty -s
+		    if [ $? -eq 0 ]; then
+			echo
 		    fi
-		done
-		auth_password=${password}
-		tty -s
-		if [ $? -eq 0 ]; then
-		    echo
 		fi
 	    fi
 
@@ -1578,38 +1622,57 @@ case "${cmd}" in
 
 	determine_outdir
 
-	echo ${container_a_port} | grep -q /
-	if [ $? -eq 0 ]; then
+	if [[ ${container_a_port} =~ ^[0-9]+$ ]]; then
+	    port_link=t
+	fi
+	if [ -z "${port_link}" ]; then
 	    # this is a directory link, not a port link
 
 	    container_a_dir_minus_one=$(dirname ${container_a_port})
 	    container_a_tgt_dir=$(basename ${container_a_port})
 
 	    if [ "${op}" == "+" ]; then
-
-		if [ ! -e "/opt/container/${container_a}/rootfs/${container_a_port}" ]; then
-		    echo "[ERROR]: /opt/container/${container_a}/rootfs/${container_a_port} does not exist"
-		    exit 1
-		fi
-
 		if [ -n "${verbose}" ]; then
-		    echo "[INFO]: linking ${container_a}:${container_a_port} to ${container_b}:${container_b_port}"
+		    echo "[INFO]: data linking ${container_a}:${container_a_port} to ${container_b}:${container_b_port}"
 		fi
 
-		mkdir -p /opt/container/data/${container_a}/${container_a_dir_minus_one}
-		(
-		    cd /opt/container/data/${container_a}/${container_a_dir_minus_one}
-		    ln -sf /opt/container/${container_a}/rootfs/${container_a_port} . 2> /dev/null
-		    if [ $? -ne 0 ]; then
-			echo "[ERROR]: unable to link ${container_a_port} into data export"
-			echo "           % cd /opt/container/data/${container_a}/${container_a_dir_minus_one}"
-			echo "           % ln -sf /opt/container/${container_a}/rootfs/${container_a_port} ."
+		if [ "${container_a}" == "localhost" ] || [ "${container_a}" == "host" ]; then
+		    host_shared_mount=t
+		    container_a="host"
+		fi
+
+		if [ -n "${host_shared_mount}" ]; then
+		    mkdir -p /opt/container/data/${container_a}/${container_a_port}
+		    if [ $? -eq 0 ]; then
+			# TODO: make the chown and chmod options
+			chown root:root /opt/container/data/${container_a}/${container_a_port}
+			chmod 1777 /opt/container/data/${container_a}/${container_a_port}
+
+			c3-cfg -n ${container_b} mount bind:/opt/container/data/${container_a}/${container_a_port}:${container_b_port}
+		    fi
+		else
+		    if [ ! -e "/opt/container/${container_a}/rootfs/${container_a_port}" ]; then
+			echo "[ERROR]: /opt/container/${container_a}/rootfs/${container_a_port} does not exist"
 			exit 1
 		    fi
-		)
 
-		if [ $? -eq 0 ]; then
-		    c3-cfg -n ${container_b} mount bind:/opt/container/data/${container_a}/${container_a_dir_minus_one}/${container_a_tgt_dir}:${container_b_port}
+		    mkdir -p /opt/container/data/${container_a}/${container_a_dir_minus_one}
+		    (
+			cd /opt/container/data/${container_a}/${container_a_dir_minus_one}
+
+			## TODO: change this to a bind mount
+			ln -sf /opt/container/${container_a}/rootfs/${container_a_port} . 2> /dev/null
+			if [ $? -ne 0 ]; then
+			    echo "[ERROR]: unable to link ${container_a_port} into data export"
+			    echo "           % cd /opt/container/data/${container_a}/${container_a_dir_minus_one}"
+			    echo "           % ln -sf /opt/container/${container_a}/rootfs/${container_a_port} ."
+			    exit 1
+			fi
+		    )
+
+		    if [ $? -eq 0 ]; then
+			c3-cfg -n ${container_b} mount bind:/opt/container/data/${container_a}/${container_a_dir_minus_one}/${container_a_tgt_dir}:${container_b_port}
+		    fi
 		fi
 	    else
 		# dropping a mount
@@ -1618,30 +1681,42 @@ case "${cmd}" in
 		fi
 
 		(
-		    cd /opt/container/data/${container_a}/${container_a_dir_minus_one}
-
-		    # TODO. this would be a lot nicer as a chroot or mount namespace 
-		    echo ${container_a_tgt_dir} | grep -q "\.\./"
-		    if [ $? -eq 0 ]; then
-			echo "[ERROR]: target path includes ../, refusing to unlink"
-			exit 1
+		    if [ "${container_a}" == "localhost" ] || [ "${container_a}" == "host" ]; then
+			host_shared_mount=t
+			container_a="host"
 		    fi
 
-		    if [ -n "${verbose}" ]; then
-			echo "[INFO]: rm -rf /opt/container/data/${container_a}/${container_a_dir_minus_one}/${container_a_tgt_dir}"
-		    fi
-		    rm -rf ${container_a_tgt_dir}
-		    if [ $? -ne 0 ]; then
-			echo "[ERROR]: unable to unlink ${container_a_port} from data export"
-			echo "           % cd /opt/container/data/${container_a}/${container_a_dir_minus_one}"
-			echo "           % rm -rf ${container_a_tgt_dir}"
-			exit 1
+		    if [ -n "${host_shared_mount}" ]; then
+			rm -rf /opt/container/data/${container_a}/${container_a_port}
+			if [ $? -eq 0 ]; then
+			    c3-cfg -n ${container_b} mount -bind:/opt/container/data/${container_a}/${container_a_dir_minus_one}/${container_a_tgt_dir}:${container_b_port}
+			fi
+		    else
+			cd /opt/container/data/${container_a}/${container_a_dir_minus_one}
+
+			# TODO. this would be a lot nicer as a chroot or mount namespace
+			echo ${container_a_tgt_dir} | grep -q "\.\./"
+			if [ $? -eq 0 ]; then
+			    echo "[ERROR]: target path includes ../, refusing to unlink"
+			    exit 1
+			fi
+
+			if [ -n "${verbose}" ]; then
+			    echo "[INFO]: rm -rf /opt/container/data/${container_a}/${container_a_dir_minus_one}/${container_a_tgt_dir}"
+			fi
+			rm -rf ${container_a_tgt_dir}
+			if [ $? -ne 0 ]; then
+			    echo "[ERROR]: unable to unlink ${container_a_port} from data export"
+			    echo "           % cd /opt/container/data/${container_a}/${container_a_dir_minus_one}"
+			    echo "           % rm -rf ${container_a_tgt_dir}"
+			    exit 1
+			fi
+
+			if [ $? -eq 0 ]; then
+			    c3-cfg -n ${container_b} mount -bind:/opt/container/data/${container_a}/${container_a_dir_minus_one}/${container_a_tgt_dir}:${container_b_port}
+			fi
 		    fi
 		)
-
-		if [ $? -eq 0 ]; then
-		    c3-cfg -n ${container_b} mount -bind:/opt/container/data/${container_a}/${container_a_dir_minus_one}/${container_a_tgt_dir}:${container_b_port}
-		fi
 	    fi
 
 	    # activate the mount
