cube-console: error if container name is not recogized
When running cube-console on dom0, an unknown container was dropping
to cube-essential's namespace shell. This isn't expected, so instead
if we don't find a container manager, we error and indicate that the
container name is not known.

Also, we make the regex matching for dom0 and essential to be strict
to prevent typo's from attempting a shell to a container.

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>

diff --git a/meta-cube/recipes-support/overc-utils/source/cube-console b/meta-cube/recipes-support/overc-utils/source/cube-console
--- a/meta-cube/recipes-support/overc-utils/source/cube-console
+++ b/meta-cube/recipes-support/overc-utils/source/cube-console
@@ -104,6 +104,10 @@ function do_console()
 	    cmd="script -q -c '/sbin/agetty -J -' /dev/null"
 	else
 	    mgr=$(cube-cfg -o /opt/container/${target}/ get cube.container.mgr)
+	    if [ -z "${mgr}" ]; then
+		echo "[ERROR]: container \"${target}\" not found"
+		exit 1
+	    fi
 	    echo ${mgr} | grep -q runc
 	    if [ $? -eq 0 ]; then
 		cmd="${mgr} exec -- ${target} script -q -c '/sbin/agetty -J -' /dev/null"
@@ -150,7 +154,7 @@ function enter_console
 	    fi
 	    echo "$x"
 	    ;;
-	*essential*)
+	essential)
 	    if [ -n "${we_are_dom0}" ]; then
 		do_console essential
 	    else
@@ -158,7 +162,7 @@ function enter_console
 		exit 1
 	    fi
 	    ;;
-	*dom0*)
+	dom0)
 	    do_console dom0 login
 	    ;;
 	*)
