cube: rework networking support
This wide ranging commit reworks the configuration of networking in an OverC
configuration.

Among the changes are:

 - ansible is only used to configure essential and not the networking configuration
 - containers themselves play no part in the network configuration, the logic and
   control structure is in networking hooks
 - dhcp and DNS is always (and only) on the network prime
 - the installer does not have absolute control over the networking, since all runtime
   logic is in hooks, we can dynamically re-configure the system
 - Existing naming in OverC configuration files continues to work

 - dom0 is always at 192.168.42.3
 - essential is always at 192.168.2
 - netprime is always at 192.168.1

 - if dom0 is both the netprime and itself, it is reachable by either IP

 - resolv.conf is written by the startup hooks, not the containers themselves

 - We have an updated oci-network hook that is capable of reading configuration
   values and configuing a runc basec container (system or not)

 - We have a new hook: cube-network, which has the same functionality as oci-network
   .. except for cubes

 - We have a new hook: cube-netprime, which is added to whatever container is the
   netprime and is responsible for setting up dnsmasq.

 - The netprime is explicitly configured for ip forwarding and NAT translation

 - oci configuration is capable of supporting X, hence cube-desktop

The existing ansible files are left for reference, since their logic may be required
in the hooks in the future.

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>

diff --git a/meta-cube/recipes-support/overc-conftools/source/cube-network b/meta-cube/recipes-support/overc-conftools/source/cube-network
--- a/meta-cube/recipes-support/overc-conftools/source/cube-network
+++ b/meta-cube/recipes-support/overc-conftools/source/cube-network
@@ -1,12 +1,28 @@
 #/bin/bash
 
-# we ge an action + startup json
+# we ge an action + cube name
 action=$1
 shift
+cubedir=$1
 
-# yank what we need out of the json
-pid=$(echo "$@" | jq .pid)
-veth_name=$(eval echo veth${pid})
+cd $cubedir
+
+cubename=$(basename $cubedir)
+
+count=0
+while [ $count -lt 10 ]; do
+    pid=$(machinectl show ${cubename} | grep Leader | cut -f2 -d=)
+    if [ -z "${pid}" ]; then
+	echo "failed to get pid $count" >> /tmp/cube-hook.log
+	let count=$count+1
+	sleep 0.5
+    else
+	echo "got pid $pid on try $count" >> /tmp/cube-hook.log
+	count=10
+    fi
+done
+
+veth_name=$(eval echo veth-${cubename})
 
 if [ "${action}" = "up" ]; then
     echo "${pid}" > .cube.pid
@@ -28,18 +44,29 @@ if [ "${action}" = "up" ]; then
     # veth-br-int is inserted into the container, and will be consistent across
     # containers.
     #
-    ip link add dev ${veth_name} type veth peer name veth-br-int
+    # This is done by pflask, so we can skip it for now
+    # ip link add dev ${veth_name} type veth peer name veth-br-int
     
     # Add the veth that stays in essential to the ovs-bridge. This gets us
     # connectivity to the network prime, and hence the outside world
-    ovs-vsctl add-port br-int ${veth_name}
+    count=0
+    while [ $count -lt 10 ]; do
+	ovs-vsctl add-port br-int ${veth_name}
+	if [ $? -ne 0 ]; then
+	    let count=$count+1
+	    sleep 0.5
+	else
+	    count=10
+	fi
+    done
 
     # Bring up the interface we just added to the bridge. It must be up so dhcp
     # can get an ip address.
     ip link set dev ${veth_name} up
 
     # push the container veth endpoint into the container network namespace
-    ip link set veth-br-int netns ${pid}
+    # NOTE: also done by pflask
+    # ip link set veth-br-int netns ${pid}
 
     # TODO: we should have a third networking mode "self", which means that
     #       we'd make the veth available and let the container itself set up
@@ -52,11 +79,10 @@ if [ "${action}" = "up" ]; then
     #   3) default route configuration
     #
     nsenter -t ${pid} -n --preserve-credentials ip link set dev lo up
-    nsenter -t ${pid} -n --preserve-credentials ip link set dev veth-br-int up
-
+    nsenter -t ${pid} -n --preserve-credentials ip link set dev ${veth_name} up
     if [ "${network}" == "dynamic" ]; then
-	nsenter -t ${pid} -n --preserve-credentials dhclient veth-br-int
-	primary_ip=$(nsenter -t ${pid} -n ip -o -4 addr list veth-br-int | awk '{print $4}' | cut -d/ -f1)
+	nsenter -t ${pid} -n --preserve-credentials dhclient ${veth_name}
+	primary_ip=$(nsenter -t ${pid} -n ip -o -4 addr list ${veth_name} | awk '{print $4}' | cut -d/ -f1)
     else
 	# the ip must be in the format of address/mask, i.e.: 192.168.42.101/24
 	ip=$(cat cube.network.ip)
@@ -64,42 +90,64 @@ if [ "${action}" = "up" ]; then
 	    echo "ERROR: static networking selected and no IP provided"
 	    exit 1
 	fi
-	nsenter -t ${pid} -n --preserve-credentials ip addr add $ip dev veth-br-int
-	primary_ip=$(echo $ip | cut -d/ -f1)
+	
+	# the first entry is the primary, any others are aliases
+	count=0
+	for i in ${ip}; do
+	    if [ ${count} -eq 0 ]; then
+		nsenter -t ${pid} -n --preserve-credentials ip addr add $i dev ${veth_name}
+		primary_ip=$(echo $i | cut -d/ -f1)
+	    else
+		nsenter -t ${pid} -n --preserve-credentials ip addr add $i dev ${veth_name}:${count}
+	    fi
+	    let count=${count}+1
+	done
     fi
 
     if [ -f "cube.network.mac" ]; then
 	mac_address=$(cat cube.network.mac)
     else
-	# OCI's use the internal mac range: xA-xx-xx-xx-xx-xx
+	# cube's use the internal mac range: x6-xx-xx-xx-xx-xx
 	last_ip_range=$(echo $primary_ip | cut -f4 -d.)
-	mac_address=$(printf "0A:00:00:00:00:%02x" ${last_ip_range})
+	mac_address=$(printf "06:00:00:00:00:%02x" ${last_ip_range})
     fi
-    nsenter -t ${pid} -n --preserve-credentials ip link set dev veth-br-int up address ${mac_address}
+    nsenter -t ${pid} -n --preserve-credentials ip link set dev ${veth_name} up address ${mac_address}
 
     gateway="192.168.42.1"
     if [ -f "cube.network.gateway" ]; then
 	gateway=$(cat cube.network.gateway)
     fi
 
-    # physical device passthrough
+    # device passthrough
+    #
+    # if no devices are passed through, then we need to set the default
+    # route to the gateway (since no config script will ever be run)
+    need_default_route=t
     if [ -f ".cube.device.network" ]; then
 	# any non virtual ethernet devices ?
 	netdevs=$(cat .cube.device.network)
 	for n in ${netdevs}; do
 	    echo ${n} | grep -q veth
 	    if [ $? -ne 0 ]; then
+		# clear the default route flag, whatever ups the interface will
+		# take care of this.
+
+		need_default_route=
 		# we have a real device
 		device=$(echo ${n} | cut -f1 -d:)
+
 		# push the device into the namespace
-		ip link set ${device} netns ${pid}
+		# Note: done by pflask
+		# ip link set ${device} netns ${pid}
 
 		# setup nat and forwarding. this is what systemd-networkd does as well
 		nsenter -t ${pid} -n --preserve-credentials iptables -t nat -A POSTROUTING -o ${device} -j MASQUERADE
 		nsenter -t ${pid} -m -n -u -i -p -C --preserve-credentials sh -c 'echo 1 > /proc/sys/net/ipv4/ip_forward'
 	    fi
 	done
-    else
+    fi
+
+    if [ -n "${need_default_route}" ]; then
 	nsenter -t ${pid} -n --preserve-credentials ip route add default via ${gateway}
     fi
 
@@ -111,11 +159,8 @@ if [ "${action}" = "up" ]; then
 fi
 
 if [ "${action}" = "down" ]; then
-    path=$(echo "$@" | jq .bundlePath | sed 's%"%%g')
-    veth_name_down=$(cat ${path}/.cube.veth)
-
-    ovs-vsctl del-port br-int ${veth_name_down}
-    ip link del dev ${veth_name_down}
+    ovs-vsctl del-port br-int ${veth_name}
+    ip link del dev ${veth_name}
 
     # physical device passthrough
     if [ -n "${path}/.cube.device.network" ]; then
diff --git a/meta-cube/recipes-support/overc-utils/source/cube-cfg b/meta-cube/recipes-support/overc-utils/source/cube-cfg
--- a/meta-cube/recipes-support/overc-utils/source/cube-cfg
+++ b/meta-cube/recipes-support/overc-utils/source/cube-cfg
@@ -51,7 +51,7 @@ cat << EOF
        hook         the hook is an executable
        hook-script  the hook is a script
 
-       <type>       type of hook: prestart or poststop
+       <type>       type of hook: prestart, poststart or poststop
        <name>       full path to the hook
 
  ${0##*/} [-n <container name>] device <type>:<name>:<name>
@@ -74,6 +74,7 @@ cat << EOF
  ${0##*/} get/set:
 
    NOTE: variables with embedded / are etcd set/get operations.
+   NOTE: --append or --prepend can be used in combination with 'set'
 
    set:
      ${0##*/} [-n <container name>] [-o <output dir>] set <setting>:<value>
@@ -112,7 +113,8 @@ CONFIG_MAP[autostart]="autostart;The autostart runlevel for the container"
 CONFIG_MAP[cube.network.type]="cube.network.type;The type of container networking: static or dynamic"
 CONFIG_MAP[cube.network.ip]="cube.network.ip;<ip>/<netmask>. The ip to assign to the container (must be supplied for static network type)"
 CONFIG_MAP[cube.network.mac]="cube.network.mac;The mac address to assign to the container interface"
-CONFIG_MAP[cube.network.gateway]="cube.network.gateway;The gatway to use for the container"
+CONFIG_MAP[cube.network.gateway]="cube.network.gateway;The gateway to use for the container"
+CONFIG_MAP[cube.network.nameserver]="cube.network.nameserver;The nameserver to use for the container"
 
 if [ -z "$1" ]; then
     usage
@@ -152,6 +154,14 @@ while [ $# -gt 0 ]; do
 	--parent)
 	    parent=${2}
 	    shift
+	    ;;
+	--prepend)
+	    # used with set
+	    prepend=t
+	    ;;
+	--append)
+	    # used with set
+	    append=t
 	    ;;
 	--name)
 	    container_name_temp=${2}
@@ -310,7 +320,7 @@ clean_config_artifacts()
     fi
 
     if [ "${type}" = "hooks" ] || [ "${type}" = "all" ]; then
-	rm -f ${out_dir}/.cube.hooks.prestart ${out_dir}/.cube.hooks.poststop
+	rm -f ${out_dir}/.cube.hooks.prestart ${out_dir}/.cube.hooks.poststart ${out_dir}/.cube.hooks.poststop
     fi
 }
 
@@ -367,12 +377,17 @@ OLDIFS=$IFS
 IFS='
 '
 	    for b in $(cat ${out_dir}/.cube.hooks.prestart); do
-		echo "hook (pre) : $b" | sed 's/##space##//g'
+		echo "hook (pre start) : $b" | sed 's/##space##//g'
+	    done
+	fi
+	if [ -e "${out_dir}/.cube.hooks.poststart" ]; then
+	    for b in $(cat ${out_dir}/.cube.hooks.poststart); do
+		echo "hook (post start) : $b" | sed 's/##space##//g'
 	    done
 	fi
 	if [ -e "${out_dir}/.cube.hooks.poststop" ]; then
 	    for b in $(cat ${out_dir}/.cube.hooks.poststop); do
-		echo "hook (post): $b" | sed 's/##space##//g'
+		echo "hook (post stop): $b" | sed 's/##space##//g'
 	    done
 	fi
 IFS=$OLDIFS
@@ -418,6 +433,7 @@ generate_base_config()
                   --cap-add SYS_ADMIN \
 		  --cap-add SYS_MODULE \
                   --cap-add SYS_RESOURCE \
+                  --cap-add NET_ADMIN \
                   --cap-add SYS_TTY_CONFIG"
 
     app="/sbin/init"
@@ -440,6 +456,21 @@ IFS='
 		hooks="${hooks} --prestart ${cmd}:${args}"
 	    else
 		hooks="${hooks} --prestart ${cmd}"
+	    fi
+	done
+    fi
+    if [ -e ".cube.hooks.poststart" ]; then
+	for hook in $(cat .cube.hooks.poststart); do
+	    cmd=$(echo ${hook} | cut -d' ' -f1)
+	    count=$(echo ${hook} | wc -w)
+	    if [ $count -gt 1 ]; then
+		# the oci generation tool will take : separated items as arguments
+		# to the main executable. So we replace our spaces with : to get
+		# everything into the config.json
+		args=$(echo ${hook} | sed 's/ /:/g')
+		hooks="${hooks} --poststart ${cmd}:${args}"
+	    else
+		hooks="${hooks} --poststart ${cmd}"
 	    fi
 	done
     fi
@@ -554,9 +585,9 @@ convert_base_config_to_cube()
     fi
 
     # hooks ?
-    prestart_hooks=$(jq -r '.hooks.prestart' config.json)
-    if [ "${prestart_hooks}" != "null" ]; then
-	prestart_hooks=$(jq -r '.hooks.prestart | map("\(.path) \(.args)") | . []' config.json)
+    poststart_hooks=$(jq -r '.hooks.poststart' config.json)
+    if [ "${poststart_hooks}" != "null" ]; then
+	poststart_hooks=$(jq -r '.hooks.poststart | map("\(.path) \(.args)") | . []' config.json)
     fi
     poststop_hooks=$(jq -r '.hooks.poststop' config.json)
     if [ "${poststop_hooks}" != "null" ]; then
@@ -573,6 +604,8 @@ convert_base_config_to_cube()
     pflask_args="${pflask_args}	-p ${container_name} --uncontain -d --escape-char=255 --root ${rootfs}"
 
     echo "#!/bin/bash" > pflask.cmd
+    echo "date > /tmp/pflask-hook.log" >> pflask.cmd
+
     if [ -e "cube.console.mgr" ]; then
 	grep -q "screen-tty" cube.console.mgr
 	if [ $? -eq 0 ]; then
@@ -584,13 +617,11 @@ convert_base_config_to_cube()
     fi
     echo "pflask ${pflask_args} -- ${app}" >> pflask.cmd
 
-    if [ -n "${prestart_hooks}" ]; then
-	# let's give the container time to start. this may go away later.
-	echo "sleep 0.5" >> pflask.cmd
+    if [ -n "${poststart_hooks}" ]; then
 	OLDIFS=$IFS
 IFS='
 '
-	for h in ${prestart_hooks}; do
+	for h in ${poststart_hooks}; do
 	    # drop any "null" strings, since that means "no args"
 	    h=$(echo "${h}" | sed 's/null//g')
 
@@ -600,14 +631,34 @@ IFS='
 	    if [ $? -eq 0 ]; then
 		zztop=$(echo ${h} | sed -e 's/.*\[\(.*\)\]/\1/')
 		if [ -n "${zztop}" ]; then
+		    # drop quotes and commas
 		    zztop=$(echo ${zztop} | tr -d '"')
 		    zztop=$(echo ${zztop} | sed 's/,/ /g')
 		    h=${zztop}
 		fi
 	    fi
 
-	    # put the conditioned hook into the pflask command
-	    echo "${h}" >> pflask.cmd
+	    # was it a script call ? if it was, we need to put quotes back
+	    # arond the -c "<command>"
+	    echo ${h} | grep -q "sh -c"
+	    if [ $? -eq 0 ]; then
+		h=$(echo ${h} | sed "s/-c /-c '/")
+		h=$(echo ${h} | sed "s/$/'/")
+	    fi
+
+	    # put the conditioned hook into the pflask command, with a retry loop (since these can have timing issues)
+	    echo "count=0" >> pflask.cmd
+	    echo "while [ \$count -lt 10 ]; do" >> pflask.cmd
+	    echo "    ${h}" >> pflask.cmd
+	    echo "    if [ \$? -ne 0 ]; then" >> pflask.cmd
+	    echo "        echo \"Hook fail [\"${h}\"] (\$count)!\" >> /tmp/pflask-hook.log" >> pflask.cmd
+	    echo "        count=\`expr \$count + 1\`" >> pflask.cmd
+	    echo "        sleep 0.5" >> pflask.cmd
+	    echo "    else" >> pflask.cmd
+	    echo "        echo \"Hook success [\"${h}\"] (\$count)\" >> /tmp/pflask-hook.log" >> pflask.cmd
+	    echo "        count=10" >> pflask.cmd
+	    echo "    fi" >> pflask.cmd
+	    echo "done" >> pflask.cmd
 	done
 	IFS=$OLDIFS
     fi
@@ -762,6 +813,8 @@ case "${cmd}" in
 
 	    if [ "${type}" == "prestart" ]; then
 		echo "${hookname}" >> ${out_dir}/.cube.hooks.prestart
+	    elif [ "${type}" == "poststart" ]; then
+		echo "${hookname}" >> ${out_dir}/.cube.hooks.poststart
 	    elif [ "${type}" == "poststop" ]; then
 		echo "${hookname}" >> ${out_dir}/.cube.hooks.poststop
 	    else
@@ -862,7 +915,16 @@ case "${cmd}" in
 	    fi
 	else
 	    if [ "${cmd}" = "set" ]; then
-		echo "${value}" > ${out_dir}/${db_var}
+		if [ -f ${out_dir}/${db_var} ]; then
+		    previous=$(cat ${out_dir}/${db_var})
+		fi
+		if [ -n "${prepend}" ]; then
+		    echo "${value} ${previous}" > ${out_dir}/${db_var}
+		elif [ -n "${append}" ]; then
+		    echo "${previous} ${value}" > ${out_dir}/${db_var}
+		else
+		    echo "${value}" > ${out_dir}/${db_var}
+		fi
 	    else
 		if [ -e "${out_dir}/${db_var}" ]; then
 		    cat "${out_dir}/${db_var}"
