overc: support container update using rpm feeds
overc-system-agent: add containers updating use rpm feeds,
and snapshot command for containers.

Signed-off-by: fupan li <fupan.li@windriver.com>

diff --git a/meta-pod/recipes-support/overc-system-agent/files/overc-system-agent-1.2/container-scripts/dom0 b/meta-pod/recipes-support/overc-system-agent/files/overc-system-agent-1.2/container-scripts/dom0
--- a/meta-pod/recipes-support/overc-system-agent/files/overc-system-agent-1.2/container-scripts/dom0
+++ b/meta-pod/recipes-support/overc-system-agent/files/overc-system-agent-1.2/container-scripts/dom0
@@ -36,6 +36,8 @@ Usage: $0 [OPTION] ...
 	update container image with url
   -U
 	update container image
+  -U -r -n <container name>
+        update container using rpm packages
   -S -n <container name>
 	start container
   -K -n <container name>
@@ -207,6 +209,11 @@ list_snapshots() {
 	$OVERC_CCTL histlist -n $container
 }
 
+snapshot() {
+        local container=$1
+	$OVERC_CCTL snapshot -n $container
+}
+
 pull_single_image() {
 	local url=$1
 	local tmp=`mktemp -d `
@@ -290,6 +297,33 @@ list_container() {
 	$DOM0_CTL list
 }
 
+runcmd_in_container() {
+        $DOM0_CTL exec-cmd -n $1 $2
+}
+
+update_container() {
+       if [ $rpm -eq 1 ]; then
+               verify_arg_set container
+               runcmd_in_container $container "smart update"
+               if [ ! $? -eq 0 ]; then
+                       echo "smart update failed in container $container"
+                       exit 1
+               fi
+               runcmd_in_container $container "smart newer"
+               if [ ! $? -eq 0 ]; then
+                       return 0
+               fi
+
+               echo "snapshots on container: $container"
+               snapshot $container
+               runcmd_in_container $container "smart upgrade -y"
+                                                                                
+       else            
+               echo "Pull on container image"
+               pull_image
+       fi
+}
+
 delete_container() {
 	local container=$1
 
@@ -331,9 +365,14 @@ verify_arg_set() {
 
 force=0
 command=""
-while getopts :asUSKLBRAn:fu:b:d opt
+rpm=0
+
+while getopts :asprUSKLBRAn:fu:b: opt
 do
 	case $opt in
+        r)
+               rpm=1
+               ;;
 	n)
 		if [ -n "$container" ]; then
 			echo "Error! Container specified more than once"
@@ -392,6 +431,9 @@ do
 	d)
 		set_command "delete"
 		;;
+        p)
+                set_command "snapshot"
+                ;;
 	*)
 		usage
 		exit 1
@@ -417,8 +459,7 @@ case "${command}" in
 		pull_single_image $container_url
 		;;
 	update)
-		echo "Pull on container image"
-		pull_image
+		update_container 
 		;;
 	start)
 		verify_arg_set container
@@ -439,6 +480,11 @@ case "${command}" in
 		verify_arg_set container
 		echo "List snapshots on container: $container"
 		list_snapshots $container
+		;;
+	snapshot)
+		verify_arg_set container
+		echo "snapshots on container: $container"
+		snapshot $container
 		;;
 	rollback)
 		verify_arg_set container
